import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT||'/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM||'/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4305',out='/tmp/bmq-i18n-lanes/c-production',results=[];
const vis=l=>l.filter({visible:true}),button=(p,name)=>['EN','VI'].includes(name)?p.locator('nav[aria-label="Fixture language"] button').filter({hasText:name}):vis(p.getByRole('button',{name,exact:true}));
const titles={products:['Quản lý sản phẩm','Product management'],inventory:['Xuất-nhập-tồn NVL Q7','Q7 material inventory'],materials:['Danh mục nguyên vật liệu từ Giá vốn','Material catalog from COGS'],system:['Dashboard giám sát controller','Controller monitoring dashboard'],planning:['Kế hoạch sản xuất - Xưởng Q7','Q7 Workshop Production Plan'],shifts:['Tạo ca sản xuất','Create production shift'],qa:['QA & nhập kho thành phẩm Q7','Q7 QA & finished goods receiving']};
async function run(slug,lang,width,mode,fn){const id=`${slug}-${lang}-${width}-${mode}`,ctx=await browser.newContext({viewport:{width,height:1000}});const unexpected=[],errors=[];
 await ctx.addInitScript(lang=>{if(!sessionStorage.getItem('initialized')){localStorage.setItem('app-language',lang);sessionStorage.setItem('initialized','1');}},lang);
 await ctx.route('**/*',r=>{if(r.request().url().startsWith(origin+'/'))return r.continue();if(r.request().url().startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});unexpected.push(r.request().url());return r.abort();});
 const p=await ctx.newPage();p.setDefaultTimeout(4000);p.on('pageerror',e=>errors.push(e.message));
 try{await p.goto(`${origin}/${slug}?fixture=${mode}`);await vis(p.getByText(slug==='shifts'&&width===390?en(lang,'Tạo ca','New shift'):titles[slug][lang==='en'?1:0],{exact:true})).first().waitFor();await fn(p);assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);assert.deepEqual(unexpected,[]);assert.deepEqual(errors,[]);results.push({id,passed:true});console.log('PASS',id);}catch(e){results.push({id,passed:false,error:e.message});console.log('FAIL',id,e.message);await fs.writeFile(`${out}/${id}-failure.txt`,await p.locator('body').innerText());}finally{await ctx.close();await fs.writeFile(out+'/browser-results.json',JSON.stringify(results,null,2));}}
const en=(lang,vi,english)=>lang==='en'?english:vi;
try{
for(const slug of Object.keys(titles).filter(s=>!process.env.C_PAGES||process.env.C_PAGES.split(',').includes(s)))for(const lang of ['en','vi'])for(const width of [390,1440]){
await run(slug,lang,width,'data',async p=>{
 const other=lang==='en'?'vi':'en';
 if(slug==='products'){
 await p.getByRole('combobox').click();await p.getByRole('option').filter({hasText:'Bánh giữ nguyên'}).click();const numbers=p.locator('input[type="number"]');await numbers.nth(0).fill('5');await numbers.nth(1).fill('250');
 await button(p,other.toUpperCase()).evaluate(el=>el.click());await vis(p.getByText(slug==='shifts'&&width===390?en(other,'Tạo ca','New shift'):titles[slug][other==='en'?1:0],{exact:true})).first().waitFor();assert.equal(await numbers.nth(0).inputValue(),'5');await button(p,en(other,'Lưu thông số tem','Save label specifications')).click();await p.locator('[data-product-label-save-success]').waitFor();
 const write=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.table==='product_label_specs'&&c.operations.some(o=>o.method==='upsert')));const payload=write.operations.find(o=>o.method==='upsert').args;delete payload[0].updated_at;assert.deepEqual(payload,[{sku_id:'sku-1',sku_code:'SKU-KEEP',product_name:'Bánh giữ nguyên',shelf_life_days:5,net_weight_value:250,net_weight_unit:'g',traceability_sheet_url:null,is_label_scan_required:true},{onConflict:'sku_id'}]);
 } else if(slug==='inventory'){
 await p.getByRole('tab',{name:en(lang,'Nhập kho','Receiving'),exact:true}).click();await p.locator('#q7-receipt-item').click();await p.getByRole('option').filter({hasText:'Bột giữ nguyên'}).click();await p.locator('#q7-receipt-qty').fill('12.5');await p.locator('#q7-receipt-note').fill('Ghi chú $& giữ nguyên');await button(p,en(lang,'Ghi nhận nhập Q7','Record Q7 receipt')).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='record_q7_inventory_receipt'));await p.locator('[toast-close]').evaluateAll(els=>els.forEach(el=>el.click()));const receipt=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='record_q7_inventory_receipt'));assert.equal(receipt.args.p_quantity,12.5);assert.equal(receipt.args.p_unit,'kg');assert.equal(receipt.args.p_note,'Ghi chú $& giữ nguyên');
 await p.getByRole('tab',{name:en(lang,'Audit tồn đầu','Opening balance audit'),exact:true}).click();await p.locator('#q7-opening-item').click();await p.getByRole('option').filter({hasText:'Bột giữ nguyên'}).click();await button(p,en(lang,'Ghi audit tồn đầu Q7','Record Q7 opening balance audit')).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='backfill_q7_inventory_opening'));await p.locator('[toast-close]').evaluateAll(els=>els.forEach(el=>el.click()));const opening=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='backfill_q7_inventory_opening'));assert.equal(opening.args.p_opening_qty,null);assert.equal(opening.args.p_unit,'kg');
 await p.getByRole('tab',{name:en(lang,'Lịch sử','History'),exact:true}).click();await p.getByText('Ghi chú giữ nguyên',{exact:true}).waitFor();assert.ok((await p.locator('body').innerText()).includes('12,5'));
 await p.getByRole('tab',{name:en(lang,'Phiếu ký','Signed issues'),exact:true}).click();await p.getByTestId('q7-signed-material-issue-file-upload').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await p.getByText(en(lang,'Chỉ nhận tệp PDF.','Only PDF files are accepted.'),{exact:true}).waitFor();await button(p,other.toUpperCase()).evaluate(el=>el.click());await p.getByText(en(other,'Chỉ nhận tệp PDF.','Only PDF files are accepted.'),{exact:true}).waitFor();await p.getByTestId('q7-material-issue-confirm-open-ready').click();await p.getByRole('alertdialog').waitFor();await p.getByRole('alertdialog').getByRole('button',{name:en(other,'Huỷ','Cancel'),exact:true}).click();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.rpc==='confirm_q7_material_issue').length),0);
 } else if(slug==='materials'){
 if(width===390){await p.getByRole('button').filter({hasText:'Bột giữ nguyên'}).click();await button(p,en(lang,'Điều chỉnh thông tin NVL','Edit material details')).click();}else{await button(p,en(lang,'Sửa','Edit')).first().click();}const dialog=p.getByRole('dialog');await dialog.waitFor();await dialog.locator('textarea').fill('Lý do giữ nguyên');await dialog.locator('input').nth(1).fill('Bột mới giữ nguyên');await button(p,other.toUpperCase()).evaluate(el=>el.click());await dialog.getByText(en(other,'Tên NVL chuẩn','Canonical material name'),{exact:true}).waitFor();await dialog.getByRole('button',{name:en(other,'Lưu cập nhật','Save changes'),exact:true}).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='update_canonical_material'));const call=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='update_canonical_material'));assert.deepEqual(call.args,{p_material_id:'material-1',p_expected_version:2,p_patch:{canonical_name:'Bột mới giữ nguyên'},p_reason:'Lý do giữ nguyên',p_request_id:null});
 for(const name of ['Products using this material','Q7 material issues','Suppliers & payment requests','Needs confirmation']){await p.getByRole('tab',{name:other==='en'?name:{'Products using this material':'Sản phẩm sử dụng','Q7 material issues':'Phiếu xuất kho Q7','Suppliers & payment requests':'NCC & Duyệt chi','Needs confirmation':'Cần xác nhận'}[name],exact:true}).click();}
 } else if(slug==='system'){
 await button(p,en(lang,'Bật enforced','Promote enforced')).click();const dialog=p.getByRole('alertdialog');await dialog.waitFor();await button(p,other.toUpperCase()).evaluate(el=>el.click());await dialog.getByText(en(other,'Promote nguồn sang enforced','Promote source to enforced'),{exact:true}).waitFor();await dialog.locator('textarea').fill('Đã kiểm tra giữ nguyên');await dialog.getByRole('button',{name:en(other,'Xác nhận đổi mode','Confirm mode change'),exact:true}).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='set_material_master_enforcement_mode'));const call=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='set_material_master_enforcement_mode'));assert.equal(call.args.p_new_mode,'enforced');assert.equal(call.args.p_reason,'Đã kiểm tra giữ nguyên');
 } else if(slug==='planning'){
 await p.getByText('SX-KEEP',{exact:true}).first().waitFor();await button(p,en(lang,'Sửa','Edit')).first().click();await p.getByRole('dialog').waitFor();await button(p,other.toUpperCase()).evaluate(el=>el.click());await p.getByRole('dialog').getByRole('button',{name:en(other,'Hủy','Cancel'),exact:true}).click();await button(p,en(other,'Xoá','Delete')).first().click();await p.getByRole('alertdialog').waitFor();await p.getByRole('alertdialog').getByRole('button',{name:en(other,'Hủy','Cancel'),exact:true}).click();
 } else if(slug==='shifts'){
 await vis(p.getByText('CA-KEEP',{exact:true})).first().click();await p.getByRole('dialog').waitFor();await p.getByRole('dialog').getByText(en(lang,'Công nhân ca này','Workers on this shift'),{exact:true}).waitFor();await button(p,other.toUpperCase()).evaluate(el=>el.click());await p.getByRole('dialog').getByText(en(other,'Công nhân ca này','Workers on this shift'),{exact:true}).waitFor();await p.keyboard.press('Escape');await button(p,en(other,width===390?'Tạo ca':'Tạo ca sản xuất',width===390?'New shift':'Create production shift')).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');
 } else if(slug==='qa'){
 await p.getByRole('button').filter({hasText:'QA-KEEP'}).click();await p.getByRole('dialog').getByText('Bánh giữ nguyên',{exact:true}).waitFor();await button(p,other.toUpperCase()).evaluate(el=>el.click());await p.getByRole('dialog').getByText(en(other,'Chất lượng','Quality'),{exact:true}).waitFor();await p.keyboard.press('Escape');await p.getByRole('button').filter({hasText:'SX-KEEP'}).filter({hasText:'Bánh giữ nguyên'}).click();await p.getByRole('dialog').waitFor();await p.getByRole('dialog').getByText(en(other,'Tem nhãn SKU','SKU label'),{exact:true}).waitFor();assert.equal(await p.getByRole('dialog').locator('[data-qa-inspector-autofill]').innerText(),'Nhân viên giữ nguyên');assert.ok(await p.getByRole('dialog').getByRole('button',{name:en(other,'QA pass & nhập kho','QA pass & receive stock'),exact:true}).isDisabled());await p.keyboard.press('Escape');
 }
 await button(p,other.toUpperCase()).evaluate(el=>el.click());await p.reload();await vis(p.getByText(slug==='shifts'&&width===390?en(other,'Tạo ca','New shift'):titles[slug][other==='en'?1:0],{exact:true})).first().waitFor();await fs.writeFile(`${out}/${slug}-${lang}-${width}-render.txt`,await p.locator('body').innerText());await p.screenshot({path:`${out}/${slug}-${lang}-${width}.png`,fullPage:true});
});
for(const mode of ['empty','loading','error'])await run(slug,lang,width,mode,async p=>{await p.waitForTimeout(150);const calls=await p.evaluate(()=>window.__fixtureCalls);assert.ok(calls.length>0,'actual backend queries executed');const body=await p.locator('body').innerText();if(mode==='empty')assert.ok(!body.includes('Bánh giữ nguyên')&&!body.includes('Bột giữ nguyên'));if(mode==='loading')assert.ok(await p.locator('.animate-spin,[class*="animate-pulse"]').count()>0,'actual loading indicator');if(mode==='error'&&['inventory','materials','system','planning','shifts'].includes(slug))assert.ok(/Unable|Failed|Không|SERVER/.test(body),'actual error surface');});
}
}finally{await browser.close();}
assert.equal(results.filter(r=>!r.passed).length,0,`${results.filter(r=>!r.passed).length} failed browser cases`);
