import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';
import {files,literals} from './inventory.mjs';
const baseline='/tmp/bmq-i18n-lanes/baseline/apps/web/src';
const source=f=>fs.readFileSync('src/'+f,'utf8');
const parse=(f,s)=>ts.createSourceFile(f,s,99,true,ts.ScriptKind.TSX);
const printer=ts.createPrinter({removeComments:true});
function contract(f,s){const tree=parse(f,s),out={classes:[],writes:[],businessPredicates:[],calculations:[]};function walk(n){if(ts.isJsxAttribute(n)&&n.name.getText(tree)==='className')out.classes.push(printer.printNode(ts.EmitHint.Unspecified,n,tree));if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&['insert','update','upsert','delete','rpc'].includes(n.expression.name.text))out.writes.push(printer.printNode(ts.EmitHint.Unspecified,n,tree));if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&['toLocaleString','toFixed','includes'].includes(n.expression.name.text))out.businessPredicates.push(printer.printNode(ts.EmitHint.Unspecified,n,tree));if((ts.isBinaryExpression(n)&&[ts.SyntaxKind.AsteriskToken,ts.SyntaxKind.SlashToken,ts.SyntaxKind.PercentToken].includes(n.operatorToken.kind))||(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&n.expression.expression.getText(tree)==='Math'))out.calculations.push(printer.printNode(ts.EmitHint.Unspecified,n,tree));ts.forEachChild(n,walk);}walk(tree);return out;}
test('all existing class expressions, writes, and business behavior remain exact except the approved backend-error classifier removal',()=>{for(const f of files){const b=fs.readFileSync(path.join(baseline,f),'utf8');const expected=contract(f,b);if(f==='components/q7-material-inventory/Q7SignedMaterialIssueQueue.tsx'){expected.businessPredicates=expected.businessPredicates.filter(value=>!/^lower\.includes\("(?:permission|permission denied|not allowed|unauthorized|actual|check|passed|status)"\)$/.test(value));}assert.deepEqual(contract(f,source(f)),expected,f);}});
const code=ts.transpileModule(source('i18n/production.ts'),{compilerOptions:{module:99}}).outputText;
const {productionCopy}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
test('EN/VI dictionary keys and named interpolation parameters match',()=>{assert.deepEqual(Object.keys(productionCopy.vi).sort(),Object.keys(productionCopy.en).sort());for(const key of Object.keys(productionCopy.vi)){const slots=s=>[...s.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort();assert.deepEqual(slots(productionCopy.vi[key]),slots(productionCopy.en[key]),key);assert.ok(productionCopy.en[key].trim(),key);}});
test('scoped untranslated Vietnamese literal guard has individually documented non-UI exceptions',()=>{const exceptions=JSON.parse(fs.readFileSync('scripts/i18n/c-production/literal-exceptions.json','utf8'));const remaining=files.flatMap(literals);for(const x of remaining)assert.ok(exceptions.some(e=>e.file===x.file&&e.text===x.text&&e.reason),`${x.file}:${x.line} ${x.text}`);});
