import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT||'/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM||'/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4305',out='/tmp/bmq-i18n-lanes/c-production',results=[];
const vis=l=>l.filter({visible:true}),button=(p,name)=>['EN','VI'].includes(name)?p.locator('nav[aria-label="Fixture language"] button').filter({hasText:name}):vis(p.getByRole('button',{name,exact:true}));
const titles={products:['Quản lý sản phẩm','Product management'],inventory:['Xuất-nhập-tồn NVL Q7','Q7 material inventory'],materials:['Danh mục nguyên vật liệu từ Giá vốn','Material catalog from COGS'],system:['Dashboard giám sát controller','Controller monitoring dashboard'],planning:['Kế hoạch sản xuất - Xưởng Q7','Q7 Workshop Production Plan'],shifts:['Tạo ca sản xuất','Create production shift'],qa:['QA & nhập kho thành phẩm Q7','Q7 QA & finished goods receiving']};
async function run(slug,lang,width,mode,fn){const id=`${slug}-${lang}-${width}-${mode}`,ctx=await browser.newContext({viewport:{width,height:1000}});const unexpected=[],errors=[];
 await ctx.addInitScript(lang=>{if(!sessionStorage.getItem('initialized')){localStorage.setItem('app-language',lang);sessionStorage.setItem('initialized','1');}},lang);
 await ctx.route('**/*',r=>{if(r.request().url().startsWith(origin+'/'))return r.continue();if(r.request().url().startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});unexpected.push(r.request().url());return r.abort();});
 const p=await ctx.newPage();p.setDefaultTimeout(4000);p.on('pageerror',e=>errors.push(e.message));
 try{await p.goto(`${origin}/${slug}?fixture=${mode}`);await vis(p.getByText(slug==='shifts'&&width===390?en(lang,'Tạo ca','New shift'):titles[slug][lang==='en'?1:0],{exact:true})).first().waitFor();await fn(p);assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);assert.deepEqual(unexpected,[]);assert.deepEqual(errors,[]);results.push({id,passed:true});console.log('PASS',id);}catch(e){results.push({id,passed:false,error:e.message});console.log('FAIL',id,e.message);await fs.writeFile(`${out}/${id}-failure.txt`,await p.locator('body').innerText());}finally{await ctx.close();await fs.writeFile(out+'/browser-material-flow.json',JSON.stringify(results,null,2));}}
const en=(lang,vi,english)=>lang==='en'?english:vi;
try{for(const lang of ['en','vi'])for(const width of [390,1440]){
await run('materials',lang,width,'material-flow',async p=>{
 await vis(p.getByText('Bột giữ nguyên',{exact:true})).first().click();await button(p,en(lang,'Xác nhận và lưu','Confirm and save')).waitFor();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.rpc==='confirm_material_supplier_product').length),0);
 assert.ok((await p.locator('body').innerText()).includes('25.000'),'financial display remains vi-VN');await button(p,en(lang,'Xác nhận và lưu','Confirm and save')).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='confirm_material_supplier_product'));await p.locator('[toast-close]').evaluateAll(els=>els.forEach(el=>el.click()));
 const c=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='confirm_material_supplier_product'));assert.deepEqual(c.args,{p_material_id:'material-1',p_expected_version:2,p_supplier_id:'supplier-1',p_product_sku_id:'sku-1',p_supplier_product_name:'Bột giữ nguyên',p_purchase_unit:'kg',p_scan_evidence_id:null,p_confirmed_base_quantity:null,p_confirmed_base_unit:null,p_reason:'Xác nhận sản phẩm Nhà cung cấp theo lựa chọn của người dùng.'});
 await p.locator('#payment-bulk-sync-reason').fill('Lý do đồng bộ giữ nguyên');const other=lang==='en'?'vi':'en';await button(p,other.toUpperCase()).evaluate(el=>el.click());await button(p,en(other,'Xác nhận và đồng bộ','Confirm and sync')).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='sync_material_supplier_payment_requests'));const sync=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='sync_material_supplier_payment_requests'));assert.deepEqual(sync.args,{p_material_id:'material-1',p_expected_version:2,p_supplier_product_id:'supplier-product-1',p_reason:'Lý do đồng bộ giữ nguyên'});await p.locator('[toast-close]').evaluateAll(els=>els.forEach(el=>el.click()));
 await p.getByRole('tab',{name:en(other,'Cần xác nhận','Needs confirmation'),exact:true}).click();await button(p,en(other,'Xác nhận liên kết','Confirm link')).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='link_approved_material_resolution'));const link=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='link_approved_material_resolution'));assert.deepEqual(link.args,{p_request_id:'resolution-1',p_source_table:'kitchen_inventory_items',p_source_id:'kitchen-1',p_expected_material_id:'material-1',p_reason:'Task3 reviewed exact reconciliation from queue'});
});
await run('inventory',lang,width,'data',async p=>{
 await p.getByRole('tab',{name:en(lang,'Phiếu ký','Signed issues'),exact:true}).click();await p.getByTestId('q7-material-issue-confirm-open-ready').click();const d=p.getByRole('alertdialog');await d.getByRole('button',{name:en(lang,'Xác nhận ghi sổ xuất Q7','Confirm Q7 usage posting'),exact:true}).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='confirm_q7_material_issue'));assert.deepEqual(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.rpc==='confirm_q7_material_issue')),[{rpc:'confirm_q7_material_issue',args:{p_issue_id:'ready'}}]);
});
}}finally{await browser.close();}
assert.equal(results.filter(r=>!r.passed).length,0,'Material confirmations and sync preserve canonical data');
