import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT||'/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM||'/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4305',out='/tmp/bmq-i18n-lanes/c-production',results=[];
const vis=l=>l.filter({visible:true}),button=(p,name)=>['EN','VI'].includes(name)?p.locator('nav[aria-label="Fixture language"] button').filter({hasText:name}):vis(p.getByRole('button',{name,exact:true}));
const titles={products:['Quản lý sản phẩm','Product management'],inventory:['Xuất-nhập-tồn NVL Q7','Q7 material inventory'],materials:['Danh mục nguyên vật liệu từ Giá vốn','Material catalog from COGS'],system:['Dashboard giám sát controller','Controller monitoring dashboard'],planning:['Kế hoạch sản xuất - Xưởng Q7','Q7 Workshop Production Plan'],shifts:['Tạo ca sản xuất','Create production shift'],qa:['QA & nhập kho thành phẩm Q7','Q7 QA & finished goods receiving']};
async function run(slug,lang,width,mode,fn){const id=`${slug}-${lang}-${width}-${mode}`,ctx=await browser.newContext({viewport:{width,height:1000}});const unexpected=[],errors=[];
 await ctx.addInitScript(lang=>{if(!sessionStorage.getItem('initialized')){localStorage.setItem('app-language',lang);sessionStorage.setItem('initialized','1');}},lang);
 await ctx.route('**/*',r=>{if(r.request().url().startsWith(origin+'/'))return r.continue();if(r.request().url().startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});if(r.request().url()==='chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/pdf_embedder.css')return r.fulfill({body:'',contentType:'text/css'});if(r.request().url().startsWith('chrome-extension://')||r.request().url().startsWith('chrome://'))return r.abort();unexpected.push(r.request().url());return r.abort();});
 const p=await ctx.newPage();p.setDefaultTimeout(4000);p.on('pageerror',e=>errors.push(e.message));
 try{await p.goto(`${origin}/${slug}?fixture=${mode}`);await vis(p.getByText(slug==='shifts'&&width===390?en(lang,'Tạo ca','New shift'):titles[slug][lang==='en'?1:0],{exact:true})).first().waitFor();await fn(p);assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);assert.deepEqual(unexpected,[]);assert.deepEqual(errors,[]);results.push({id,passed:true});console.log('PASS',id);}catch(e){results.push({id,passed:false,error:e.message});console.log('FAIL',id,e.message);await fs.writeFile(`${out}/${id}-failure.txt`,await p.locator('body').innerText());}finally{await ctx.close();await fs.writeFile(out+'/browser-planning-write.json',JSON.stringify(results,null,2));}}
const en=(lang,vi,english)=>lang==='en'?english:vi;
const pdf=Buffer.from('%PDF-1.4\n%fixture-bytes: 00 01 VI EN\n%%EOF\n','utf8');
try{for(const lang of ['en','vi'])for(const width of [390,1440])await run('planning',lang,width,'po-data',async p=>{
 const requests=[];await p.context().route(origin+'/mock-api/functions/v1/**',r=>{const req=r.request();requests.push({path:new URL(req.url()).pathname,body:req.postDataJSON()});if(req.url().endsWith('/po-gmail-attachment'))return r.fulfill({body:pdf,contentType:'application/pdf'});if(req.url().endsWith('/production-material-issue-pdf'))return r.fulfill({json:{status:'ready'}});throw Error('Unexpected mock endpoint');});
 await p.evaluate(()=>{window.__downloadBytes=[];const original=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{blob.arrayBuffer().then(b=>window.__downloadBytes.push(Array.from(new Uint8Array(b))));return original(blob);};});
 await p.getByText('PO-KEEP.pdf',{exact:true}).first().click();await p.waitForFunction(()=>window.__downloadBytes.length===1);assert.deepEqual(await p.evaluate(()=>window.__downloadBytes[0]),[...pdf]);assert.deepEqual(requests[0],{path:'/mock-api/functions/v1/po-gmail-attachment',body:{inboxId:'po-1',filename:'PO-KEEP.pdf'}});for(const popup of p.context().pages())if(popup!==p)await popup.close();
 await p.getByText(en(lang,'Xác nhận','Confirm'),{exact:true}).first().click();const d=p.getByRole('dialog');await d.waitFor();await d.locator('input[type="number"]').fill('17');await d.locator('textarea').fill('Ghi chú giữ nguyên');const other=lang==='en'?'vi':'en';await button(p,other.toUpperCase()).evaluate(el=>el.click());assert.equal(await d.locator('input[type="number"]').inputValue(),'17');await d.getByRole('button',{name:en(other,'Xác nhận tạo lệnh SX','Confirm production order'),exact:true}).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='production_order_items'&&c.operations.some(o=>o.method==='insert')));
 const calls=await p.evaluate(()=>window.__fixtureCalls);const ins=t=>calls.find(c=>c.table===t&&c.operations.some(o=>o.method==='insert')).operations.find(o=>o.method==='insert').args[0];assert.equal(ins('production_orders').status,'planned');assert.equal(ins('production_orders').location_code,'q7');assert.equal(ins('production_orders').source_po_inbox_id,'po-1');assert.equal(ins('production_orders').notes,'Ghi chú giữ nguyên');assert.equal(ins('production_order_items')[0].sku_id,'sku-1');assert.equal(ins('production_order_items')[0].product_name,'Bánh giữ nguyên');assert.equal(ins('production_order_items')[0].ordered_qty,12);assert.equal(ins('production_order_items')[0].planned_qty,17);assert.equal(ins('production_order_items')[0].unit,'cái');assert.equal(ins('production_order_items')[0].notes,'Đã điều chỉnh số lượng trước khi xác nhận');
});}finally{await browser.close();}
assert.equal(results.filter(r=>!r.passed).length,0,'Planning writes and attachment bytes stay canonical');
