import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ExcelJS from 'exceljs';
const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet('Mẫu giữ nguyên');sheet.addRow(['Ngày','Tên sản phẩm','Số lượng','Đơn giá']);sheet.addRow(['2026-09-09','Bánh giữ nguyên',2,10000]);const xlsxBuffer=Buffer.from(await workbook.xlsx.writeBuffer());
const {chromium}=await import('/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4303',out='/tmp/bmq-i18n-lanes/c-sales',cases=[],unexpected=[],errors=[];
async function setup(path,lang,width,mode='data'){
 const context=await browser.newContext({viewport:{width,height:1000}});
 await context.addInitScript(lang=>{if(!sessionStorage.getItem('init')){localStorage.setItem('app-language',lang);sessionStorage.setItem('init','1')}},lang);
 await context.route('**/*',async r=>{const url=r.request().url();if(url===origin+'/mock-supabase/functions/v1/kiosk-report-admin'){
 const body=r.request().postDataJSON();if(!['list','upsert_location','upsert_staff'].includes(body.action)){unexpected.push(url+':'+body.action);return r.abort()}
 await r.request().frame().page().evaluate(body=>{window.__fixtureCalls.push({edge:'kiosk-report-admin',body})},body);
 if(mode==='loading')return;
 if(mode==='error'||(mode==='save-error'&&body.action!=='list'))return r.fulfill({status:500,json:{error:'SERVER giữ nguyên $&'}});
 return r.fulfill({json:{success:true,locations:mode==='empty'?[]:[{id:'loc-1',location_code:'LOC-1',location_name:'Điểm giữ nguyên',address:'Địa chỉ giữ nguyên',active:true}],staff:[]}});
 }if(url.startsWith(origin+'/mock-supabase/')){unexpected.push(url);return r.abort()}if(url.startsWith(origin+'/'))return r.continue();if(url.startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});unexpected.push(url);return r.abort()});
 const page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`${origin}${path}?fixture=${mode}`);return {page,context};
}
async function close(p,c){try{unexpected.push(...await p.evaluate(()=>window.__unexpected||[]))}finally{await c.close()}}
const button=(p,name)=>p.getByRole('button',{name,exact:true}).filter({visible:true});
const labels={en:{facebook:'Facebook Page Management',open:'Open conversation Khách giữ nguyên $&',reply:'Reply text',send:'Send',select:'Select a conversation before replying.',crm:'Customer list',setup:'Customer setup',delivery:'Delivery staff',gps:'Attendance GPS',create:'Create delivery staff member',save:'Save staff member',empty:'No delivery staff yet.',full:'Full name',phone:'Phone number',salary:'Monthly salary',newCustomer:'Customer name'},vi:{facebook:'Quản lý Facebook Page',open:'Mở hội thoại Khách giữ nguyên $&',reply:'Nội dung trả lời',send:'Gửi',select:'Chọn hội thoại trước khi trả lời.',crm:'Danh sách khách hàng',setup:'Thiết lập khách hàng',delivery:'Nhân viên giao hàng',gps:'GPS chấm công',create:'Tạo nhân viên giao hàng',save:'Lưu nhân viên',empty:'Chưa có nhân viên giao hàng.',full:'Họ và tên',phone:'Số điện thoại',salary:'Lương tháng',newCustomer:'Tên khách hàng'}};
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Messenger ${lang} ${width}: imported page and hooks, send payload, switching/reload`,async()=>{
 const {page:p,context:c}=await setup('/facebook-messenger',lang,width);try{const l=labels[lang],other=lang==='en'?'vi':'en';await p.getByRole('heading',{name:l.facebook,exact:true}).waitFor();await button(p,l.open).click();await p.getByText('Nội dung giữ nguyên $&',{exact:true}).waitFor();await p.getByLabel(l.reply,{exact:true}).fill('  Tin nhắn giữ nguyên $&  ');await button(p,other.toUpperCase()).click();assert.equal(await p.getByLabel(labels[other].reply,{exact:true}).inputValue(),'  Tin nhắn giữ nguyên $&  ');await button(p,labels[other].send).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.function==='facebook-messenger-send'));const calls=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.function==='facebook-messenger-send'));assert.equal(calls.length,1);assert.equal(calls[0].options.body.conversation_id,'conv-1234');assert.equal(calls[0].options.body.text,'Tin nhắn giữ nguyên $&');assert.ok(calls[0].options.body.idempotency_key);await p.reload();await p.getByRole('heading',{name:labels[other].facebook,exact:true}).waitFor();assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);await p.screenshot({path:`${out}/messenger-${lang}-${width}.png`,fullPage:true});cases.push({page:'FacebookMessengerInbox',lang,width,states:['data','thread','attachment metadata','switch','reload','send payload']})}finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`CRM ${lang} ${width}: imported page, customer dialogs and canonical staff salary/phone payload`,async()=>{
 const {page:p,context:c}=await setup('/crm',lang,width);try{const l=labels[lang],other=lang==='en'?'vi':'en';await p.getByText('Khách hàng giữ nguyên $&',{exact:true}).filter({visible:true}).first().waitFor();await button(p,l.setup).click();await p.getByRole('dialog').waitFor();await p.getByRole('dialog').getByRole('button',{name:lang==='en'?'Close':'Đóng',exact:true}).waitFor();await p.getByText(l.newCustomer,{exact:true}).waitFor();await p.evaluate(lang=>window.__fixtureSetLanguage(lang),other);await p.getByText(labels[other].newCustomer,{exact:true}).waitFor();await p.keyboard.press('Escape');await p.getByRole("tab",{name:labels[other].delivery,exact:true}).click();await p.getByText(labels[other].create,{exact:true}).waitFor();await p.getByPlaceholder(other==='en'?'Example: Nguyễn Văn A':'VD: Nguyễn Văn A').fill('Nhân viên giữ nguyên');const card=p.locator('[class]').filter({has:p.getByText(labels[other].create,{exact:true})});await p.locator('input').nth(1).fill('0901234567');await p.locator('input').nth(2).fill('12000000');await button(p,labels[other].save).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='delivery_staff'&&c.operations.some(o=>o.method==='insert')));const calls=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='delivery_staff').flatMap(c=>c.operations.filter(o=>o.method==='insert')));assert.deepEqual(calls[0].args[0],{full_name:'Nhân viên giữ nguyên',phone_raw:'0901234567',phone_normalized:'84901234567',monthly_salary_vnd:12000000,active:true});assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);cases.push({page:'MiniCrm',lang,width,states:['customers','setup dialog','switch','delivery panel','canonical staff payload']});await p.screenshot({path:`${out}/crm-${lang}-${width}.png`,fullPage:true});}finally{await close(p,c)}
});
test.after(async()=>{await browser.close();await fs.writeFile(`${out}/browser-results.json`,JSON.stringify({cases,unexpected,errors},null,2));assert.deepEqual(unexpected,[]);assert.deepEqual(errors,[])});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Knowledge editor/workbench ${lang} ${width}: actual parse and evidence/lock contracts`,async()=>{
 const {page:p,context:c}=await setup('/knowledge-fixture',lang,width);try{
 await button(p,lang==='en'?'Edit configuration':'Chỉnh sửa cấu hình').click();
 const lock=button(p,lang==='en'?'Lock contract':'Khóa contract');assert.equal(await lock.isDisabled(),true);
 await p.getByRole('button',{name:/PO TEST-001/}).click();
 await button(p,lang==='en'?'Test parsing on this PO':'Chạy test parse trên PO này').click();
 await p.getByText('Điểm giữ nguyên',{exact:true}).waitFor();
 await button(p,lang==='en'?'Save evidence':'Lưu evidence').click();
 const evidence=await p.evaluate(()=>window.__contract.test_evidence[0]);assert.equal(evidence.source,'email_body');assert.equal(evidence.source_label,'Nội dung email');assert.equal(evidence.input_snippet,'1. Điểm giữ nguyên 2: đổi 1');assert.equal(evidence.item_count,1);assert.equal(evidence.expected_output,'Điểm giữ nguyên: 2');assert.equal(evidence.pass,true);
 await lock.click();assert.equal(await p.evaluate(()=>window.__contract.status),'locked');
 const other=lang==='en'?'vi':'en';await button(p,other.toUpperCase()).click();await button(p,other==='en'?'Unlock':'Mở khóa').waitFor();assert.equal(await p.getByPlaceholder(other==='en'?'Example: Tier 1 dealer - Anh Thanh Knowledge':'Ví dụ: Đại lý cấp 1 - Anh Thanh Knowledge').inputValue(),'Profile giữ nguyên');
 await button(p,other==='en'?'Create new version':'Tạo version mới').last().click();assert.equal(await p.evaluate(()=>window.__approvedContract.status),'locked');
 cases.push({page:'KnowledgeBaseProfileEditor + ParseTestWorkbench',lang,width,states:['configuration','parse','evidence','lock','switch','version action'],canonicalEvidence:evidence});
 }finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Sales PO ${lang} ${width}: actual quick view, calculations, save payload and CSV bytes`,async()=>{
 const {page:p,context:c}=await setup('/sales-po-inbox',lang,width);try{
 await button(p,lang==='en'?'Quick view':'Xem nhanh').click();const dialog=p.getByRole('dialog');await dialog.waitFor();
 const product=dialog.getByPlaceholder(lang==='en'?'Product / delivery location name':'Tên sản phẩm / điểm giao');assert.equal(await product.inputValue(),'Bánh giữ nguyên');
 const nums=dialog.locator('tbody input[type=number]');await nums.nth(0).fill('3');assert.equal(await nums.nth(2).inputValue(),'30000');await p.evaluate(l=>window.__fixtureSetLanguage(l),lang==='en'?'vi':'en');assert.equal(await nums.nth(0).inputValue(),'3');assert.equal(await nums.nth(2).inputValue(),'30000');await p.evaluate(l=>window.__fixtureSetLanguage(l),lang);assert.equal(await button(p,lang==='en'?'Post revenue':'Đẩy doanh thu').isDisabled(),true);
 await button(p,lang==='en'?'Parse email body':'Parse nội dung email').click();await p.getByText(lang==='en'?'Overwrite unsaved changes?':'Ghi đè thay đổi chưa lưu?',{exact:true}).waitFor();await button(p,lang==='en'?'Cancel':'Huỷ').click();
 await button(p,lang==='en'?'Save PO':'Lưu PO').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='customer_po_inbox'&&c.operations.some(o=>o.method==='update')));
 const updates=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='customer_po_inbox').flatMap(c=>c.operations.filter(o=>o.method==='update')).map(o=>o.args[0]));const payload=updates.at(-1);assert.equal(payload.production_items[0].qty,3);assert.equal(payload.production_items[0].unit_price,10000);assert.equal(payload.production_items[0].line_total,30000);assert.equal(payload.production_items[0].unit,'cái');assert.equal(payload.production_items[0].line_source,'manually_edited');assert.equal(payload.production_items[0].product_name,'Bánh giữ nguyên');assert.equal(payload.total_amount,22000);assert.equal(payload.subtotal_amount,20000);assert.equal(payload.vat_amount,2000);assert.equal(payload.raw_payload.manual_summary.subtotal_mismatch_warning,true);
 const other=lang==='en'?'vi':'en';await p.evaluate(l=>window.__fixtureSetLanguage(l),other);await p.getByText(other==='en'?'✅ Saved successfully: TEST-001':'✅ Lưu thành công: TEST-001',{exact:true}).waitFor();await p.keyboard.press('Escape');
 await p.reload();await button(p,other==='en'?'Export reconciliation CSV':'Xuất CSV đối soát').waitFor();await fs.writeFile(`${out}/export-before-${lang}-${width}.txt`,await p.locator('body').innerText());const [file]=await Promise.all([p.waitForEvent('download'),button(p,other==='en'?'Export reconciliation CSV':'Xuất CSV đối soát').click()]);const bytes=await fs.readFile(await file.path());assert.deepEqual(bytes,await fs.readFile(new URL('./expected-export.csv',import.meta.url)));assert.equal(bytes.subarray(0,3).toString('hex'),'efbbbf');assert.ok(bytes.toString().includes('received_at,customer_name,po_number,subject,po_mode,match_status,full_snapshot_total,base_amount,delta_amount,posted_amount,requires_review,review_decision,reviewed_at,posted_at'));await fs.writeFile(`${out}/export-${lang}-${width}.csv`,bytes);
 cases.push({page:'MiniCrm sales PO + SalesPoQuickViewEditor',lang,width,states:['quick view','quantity calculation','dirty gate','overwrite dialog cancel','save payload','persistent status switch','CSV bytes'],payload});
 }finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Messenger ${lang} ${width}: loading/error/empty/disabled/expired/reconciliation/readonly/candidates`,async()=>{
 for(const mode of ['loading','error','empty','disabled','expired','blocked','readonly','candidates','disconnected','save-error']){
 const {page:p,context:c}=await setup('/facebook-messenger',lang,width,mode);try{
 if(mode==='loading')await p.getByRole('heading',{name:lang==='en'?'Checking Facebook Page connection':'Đang kiểm tra kết nối Facebook Page'}).waitFor();
 else if(mode==='error')await p.getByRole('heading',{name:lang==='en'?'Unable to check Facebook Page connection':'Không thể kiểm tra kết nối Facebook Page'}).waitFor();
 else if(mode==='empty')await p.getByText(lang==='en'?'No Facebook Messenger conversations yet. Messages will appear here when the webhook syncs.':'Chưa có hội thoại Facebook Messenger nào. Khi webhook đồng bộ, tin nhắn sẽ xuất hiện ở đây.',{exact:true}).waitFor();
 else if(mode==='disconnected')await p.getByRole('heading',{name:lang==='en'?'Facebook Page is not connected':'Chưa kết nối Facebook Page'}).waitFor();
 else if(mode==='candidates'){await p.getByRole('heading',{name:lang==='en'?'Select a Facebook Page':'Chọn Facebook Page'}).waitFor();await p.getByRole('button',{name:/Page giữ nguyên/}).click();await p.getByText(lang==='en'?'Connected to Page giữ nguyên. Tokens are not stored in the browser.':'Đã kết nối Page giữ nguyên. Không lưu token trong trình duyệt.',{exact:true}).waitFor();const calls=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.function==='facebook-page-connect'&&c.options.body.action==='finalize_candidate'));assert.deepEqual(calls[0].options.body,{action:'finalize_candidate',candidate_id:'candidate-1'});}
 else {await button(p,labels[lang].open).click();if(mode==='save-error'){await p.getByLabel(labels[lang].reply,{exact:true}).fill('Giữ nguyên');await button(p,labels[lang].send).click();await p.getByText(lang==='en'?'Unable to complete the Facebook Messenger action. Try again or contact an administrator.':'Không thể hoàn tất thao tác Facebook Messenger. Vui lòng thử lại hoặc báo quản trị viên.',{exact:true}).waitFor()}else assert.equal(await button(p,labels[lang].send).isDisabled(),true);}
 assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);cases.push({page:'FacebookMessengerInbox',lang,width,state:mode});
 }finally{await close(p,c)}}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`CRM staff panels ${lang} ${width}: kiosk/location save payloads and GPS validation`,async()=>{
 const {page:p,context:c}=await setup('/crm',lang,width);try{
 await p.getByRole('tab',{name:lang==='en'?'Sales locations':'Điểm bán',exact:true}).click();await p.getByText('Điểm giữ nguyên',{exact:true}).waitFor();
 await p.getByPlaceholder(lang==='en'?'Example: Nguyễn Huệ kiosk':'VD: Kiosk Nguyễn Huệ').fill('Điểm mới giữ nguyên');await p.getByPlaceholder(lang==='en'?'Example: KIOSK-NH':'VD: KIOSK-NH').fill('CODE-2');await p.getByPlaceholder(lang==='en'?'Operating address':'Địa chỉ vận hành').fill('Địa chỉ giữ nguyên');await button(p,lang==='en'?'Save sales location':'Lưu điểm bán').click();
 await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.edge==='kiosk-report-admin'&&c.body.action==='upsert_location'));assert.deepEqual(await p.evaluate(()=>window.__fixtureCalls.find(c=>c.edge==='kiosk-report-admin'&&c.body.action==='upsert_location').body),{action:'upsert_location',location:{location_name:'Điểm mới giữ nguyên',location_code:'CODE-2',address:'Địa chỉ giữ nguyên',active:true}});
 await p.getByRole('tab',{name:lang==='en'?'Sales staff':'Nhân viên bán hàng',exact:true}).click();await p.getByPlaceholder(lang==='en'?'Example: Nguyễn Văn A':'VD: Nguyễn Văn A').fill('Nhân viên giữ nguyên');await p.getByPlaceholder(lang==='en'?'Example: 0966998999':'VD: 0966998999').fill('0901234567');await p.getByPlaceholder(lang==='en'?'Example: 9000000':'VD: 9000000').fill('9000000');await button(p,lang==='en'?'Save staff member':'Lưu nhân viên').click();
 await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.edge==='kiosk-report-admin'&&c.body.action==='upsert_staff'));assert.deepEqual(await p.evaluate(()=>window.__fixtureCalls.find(c=>c.edge==='kiosk-report-admin'&&c.body.action==='upsert_staff').body),{action:'upsert_staff',staff:{full_name:'Nhân viên giữ nguyên',phone_raw:'0901234567',location_id:'loc-1',monthly_salary_vnd:'9000000',active:true}});
 await p.getByRole('tab',{name:labels[lang].gps,exact:true}).click();await p.getByPlaceholder(lang==='en'?'Example: warehouse_tan_tao':'VD: warehouse_tan_tao').waitFor();const none=p.getByPlaceholder(lang==='en'?'None yet':'Chưa có',{exact:true});await none.nth(0).fill('10.75');await button(p,lang==='en'?'Save GPS':'Lưu GPS').click();await p.getByText(lang==='en'?'Latitude and longitude must be entered together.':'Vĩ độ và Kinh độ phải được nhập cùng nhau.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='attendance_geofence_locations'&&c.operations.some(o=>o.method==='insert')).length),0);await none.nth(1).fill('106.6');await button(p,lang==='en'?'Save GPS':'Lưu GPS').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='attendance_geofence_locations'&&c.operations.some(o=>o.method==='insert')));assert.deepEqual(await p.evaluate(()=>window.__fixtureCalls.find(c=>c.table==='attendance_geofence_locations'&&c.operations.some(o=>o.method==='insert')).operations.find(o=>o.method==='insert').args[0]),{code:'warehouse_tan_tao',name:'Kho Tân Tạo',location_type:'warehouse',kiosk_location_id:null,latitude:10.75,longitude:106.6,accepted_radius_m:20,active:true,notes:null});
 assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);cases.push({page:'MiniCrm staff panels',lang,width,states:['locations','sales staff','GPS','validation','canonical location/staff/geofence payloads']});
 }finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`CRM ${lang} ${width}: actual empty/loading/error and readonly panels`,async()=>{
 for(const mode of ['empty','loading','error','readonly']){const {page:p,context:c}=await setup('/crm',lang,width,mode);try{
 if(mode!=='readonly')await p.getByText(lang==='en'?'No matching customers found.':'Không tìm thấy khách hàng phù hợp.',{exact:true}).filter({visible:true}).waitFor();
 for(const [tab,loading,empty,error]of [
 [labels[lang].delivery,lang==='en'?'Loading delivery staff...':'Đang tải nhân viên giao hàng...',labels[lang].empty,lang==='en'?'Unable to load delivery staff. Please try again.':'Không thể tải danh sách nhân viên giao hàng. Vui lòng thử lại.'],
 [labels[lang].gps,lang==='en'?'Loading attendance GPS settings...':'Đang tải cấu hình GPS chấm công...',lang==='en'?'No attendance GPS settings yet.':'Chưa có cấu hình GPS chấm công.',lang==='en'?'Unable to load attendance GPS settings. Please try again.':'Không thể tải cấu hình GPS chấm công. Vui lòng thử lại.'],
 [lang==='en'?'Sales locations':'Điểm bán',lang==='en'?'Loading sales location reporting data...':'Đang tải dữ liệu báo cáo điểm bán...',lang==='en'?'No reporting locations yet.':'Chưa có điểm bán báo cáo.','SERVER giữ nguyên $&']]){
 await p.getByRole('tab',{name:tab,exact:true}).click();if(mode==='readonly'){await p.waitForTimeout(60);assert.equal(await button(p,labels[lang].save).count(),0)}else await p.getByText(mode==='loading'?loading:mode==='error'?error:empty,{exact:true}).waitFor();
 }
 assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);cases.push({page:'MiniCrm',lang,width,state:mode,panels:['customers','delivery','GPS','locations'],note:mode==='loading'||mode==='error'?'Customer table retains baseline empty fallback for pending/failed query; dedicated status UI exists on staff panels.':undefined});
 }finally{await close(p,c)}}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`CRM customer dialogs ${lang} ${width}: details, edit fields, cancel deletion and reactive setup validation`,async()=>{
 const {page:p,context:c}=await setup('/crm',lang,width);try{
 await p.getByRole('button',{name:(lang==='en'?'View customer details for ':'Xem thông tin khách hàng ')+'Khách hàng giữ nguyên $&',exact:true}).filter({visible:true}).click();
 let confirmed='';p.once('dialog',async d=>{confirmed=d.message();await d.dismiss()});await button(p,lang==='en'?'Delete customer':'Xoá khách hàng').click();assert.equal(confirmed,(lang==='en'?'Delete customer ':'Xoá khách hàng ')+'Khách hàng giữ nguyên $&?');assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='mini_crm_customers'&&c.operations.some(o=>o.method==='delete')).length),0);
 await button(p,lang==='en'?'Edit customer':'Sửa khách hàng').click();await p.getByRole('dialog').getByRole('heading',{name:lang==='en'?'Edit customer':'Sửa khách hàng'}).waitFor();assert.equal(await p.getByRole('dialog').locator('input').first().inputValue(),'Khách hàng giữ nguyên $&');await p.getByText(lang==='en'?'Dealer contacts / OTP sign-in phones':'Liên hệ đại lý / SĐT đăng nhập OTP',{exact:true}).waitFor();
 const other=lang==='en'?'vi':'en';await p.evaluate(l=>window.__fixtureSetLanguage(l),other);await p.getByRole('dialog').getByRole('heading',{name:other==='en'?'Edit customer':'Sửa khách hàng'}).waitFor();assert.equal(await p.getByRole('dialog').locator('input').first().inputValue(),'Khách hàng giữ nguyên $&');await p.keyboard.press('Escape');
 await button(p,labels[other].setup).click();await button(p,other==='en'?'Save customer setup':'Lưu thiết lập khách hàng').click();await p.getByText(other==='en'?'Enter a customer name':'Vui lòng nhập tên khách hàng',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='mini_crm_customers'&&c.operations.some(o=>o.method==='insert')).length),0);cases.push({page:'MiniCrm customer dialogs',lang,width,states:['details','delete confirmation cancelled','edit','switch in dialog','setup validation','no mutation for invalid setup']});
 }finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`CRM template confirmation ${lang} ${width}: actual XLSX parser, error feedback and language switch`,async()=>{
 const {page:p,context:c}=await setup('/crm',lang,width);try{
 await button(p,labels[lang].setup).click();const upload=p.locator('input[type=file][accept=".xlsx"]');
 await upload.setInputFiles({name:'invalid.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from('invalid workbook')});await p.getByText(lang==='en'?'Unable to read template file':'Đọc file mẫu thất bại',{exact:true}).waitFor();
 await upload.setInputFiles({name:'Mẫu giữ nguyên.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:xlsxBuffer});await p.getByRole('heading',{name:lang==='en'?'Confirm PO template before saving':'Xác nhận mẫu PO trước khi lưu',exact:true}).waitFor();
 const dialog=p.getByRole('dialog').last();assert.equal(await dialog.locator('tbody input').nth(1).inputValue(),'Bánh giữ nguyên');assert.equal(await dialog.locator('tbody input').nth(2).inputValue(),'2');
 const other=lang==='en'?'vi':'en';await p.evaluate(l=>window.__fixtureSetLanguage(l),other);await p.getByRole('heading',{name:other==='en'?'Confirm PO template before saving':'Xác nhận mẫu PO trước khi lưu',exact:true}).waitFor();assert.equal(await dialog.locator('tbody input').nth(1).inputValue(),'Bánh giữ nguyên');await button(p,other==='en'?'Confirm parsed content':'Xác nhận nội dung parse').click();await p.getByText(other==='en'?'PO template confirmed':'Đã xác nhận mẫu PO',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table&&c.operations.some(o=>['insert','update'].includes(o.method))).length),0);assert.deepEqual(await p.evaluate(()=>window.__unexpected),[]);cases.push({page:'MiniCrm template confirmation',lang,width,states:['invalid XLSX feedback','actual XLSX parse','confirmation dialog','switch','confirm unmodified template','no backend writes']});
 }finally{await close(p,c)}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Sales PO revenue ${lang} ${width}: actual daily posting calculation/audit and duplicate-post guard`,async()=>{
 const {page:p,context:c}=await setup('/sales-po-inbox',lang,width);try{
 await button(p,lang==='en'?'Quick view':'Xem nhanh').click();await button(p,lang==='en'?'Post revenue':'Đẩy doanh thu').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='po_revenue_post_audit'&&c.operations.some(o=>o.method==='insert')));
 const writes=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='customer_po_inbox').flatMap(c=>c.operations.filter(o=>o.method==='update')).map(o=>o.args[0]));assert.equal(writes.length,1);const payload=writes[0];assert.equal(payload.match_status,'approved');assert.equal(payload.posted_to_revenue,true);assert.equal(payload.raw_payload.revenue_post.mode,'daily_new_po');assert.equal(payload.raw_payload.revenue_post.total,22000);assert.equal(payload.raw_payload.revenue_post.subtotal,20000);assert.equal(payload.raw_payload.revenue_post.vat,2000);assert.equal(payload.raw_payload.revenue_post.delta_amount,22000);assert.equal(payload.raw_payload.revenue_post.base_amount,0);assert.equal(payload.raw_payload.revenue_post.requires_review,false);
 const audit=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.table==='po_revenue_post_audit'&&c.operations.some(o=>o.method==='insert')).operations.find(o=>o.method==='insert').args[0]);assert.equal(audit.action,'post');assert.equal(audit.decision,'posted');assert.equal(audit.amount,22000);assert.equal(audit.note,null);assert.equal(audit.actor,'mini-crm-ui');
 await button(p,lang==='en'?'Post revenue':'Đẩy doanh thu').click();await p.getByText(lang==='en'?'This PO has already been posted to revenue. Duplicate posting was blocked.':'PO này đã được đẩy doanh thu trước đó. Hệ thống đã chặn double-post.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='customer_po_inbox').flatMap(c=>c.operations.filter(o=>o.method==='update')).length),1);
 cases.push({page:'MiniCrm revenue posting',lang,width,states:['daily calculation','canonical approved status','audit payload','duplicate-post block'],payload,audit});
 }finally{await close(p,c)}
});
