# Generated by Django 5.2.11 on 2026-02-07 13:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('baker', 'Baker'), ('assistant', 'Assistant'), ('decorator', 'Decorator'), ('packer', 'Packer'), ('supervisor', 'Supervisor'), ('other', 'Other')], max_length=50)),
                ('hire_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wage_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly_salary', 'Monthly Salary')], default='monthly_salary', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('benefits_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.30'), max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='labor.employee')),
            ],
            options={
                'verbose_name': 'Employee Wage',
                'verbose_name_plural': 'Employee Wages',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('total_time_minutes', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_times', to='products.product')),
            ],
            options={
                'verbose_name': 'Production Time',
                'verbose_name_plural': 'Production Times',
                'ordering': ['-effective_date'],
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('mixing', 'Mixing'), ('shaping', 'Shaping'), ('proofing', 'Proofing'), ('baking', 'Baking'), ('cooling', 'Cooling'), ('decorating', 'Decorating'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=50)),
                ('duration_minutes', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('employees_required', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('employee_role', models.CharField(choices=[('baker', 'Baker'), ('assistant', 'Assistant'), ('decorator', 'Decorator'), ('packer', 'Packer'), ('supervisor', 'Supervisor'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('production_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='labor.productiontime')),
            ],
            options={
                'verbose_name': 'Production Phase',
                'verbose_name_plural': 'Production Phases',
                'ordering': ['id'],
            },
        ),
    ]
