import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT || '/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM || '/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4300',out='/tmp/bmq-i18n-lanes/b-purchasing';
const errors=[],unexpected=[],cases=[];
const visible=l=>l.filter({visible:true});
const button=(p,name)=>visible(p.getByRole('button',{name,exact:true}));
async function setup(route,lang,width,mode='data'){
 const c=await browser.newContext({viewport:{width,height:1000}});await c.addInitScript(lang=>localStorage.setItem('app-language',lang),lang);
 const edge=[];await c.route('**/*',r=>{const url=r.request().url();if(url===origin+'/fixture-document.svg')return r.fulfill({body:'<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50"><text x="0" y="20">QA</text></svg>',contentType:'image/svg+xml'});if(url.startsWith(origin+'/')&&['GET','HEAD'].includes(r.request().method())&&!['fetch','xhr'].includes(r.request().resourceType()))return r.continue();if(url.startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});if(mode==='receive'&&url==='https://backend.example.invalid/functions/v1/finalize-goods-receipt'){edge.push(r.request().postDataJSON());return r.fulfill({json:{success:true,receiptId:'44444444-4444-4444-8444-444444444444',payableId:'fixture-payable',totalAmount:20000,vatAmount:0,varianceSummary:{}}});}unexpected.push(url);return r.abort();});
 const p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await p.goto(`${origin}/${route}?fixture=${mode}`);await visible(p.locator('h1')).first().waitFor();return {c,p,edge};
}
const creation={
 suppliers:{button:['Add supplier','Thêm NCC'],title:['Add supplier','Thêm nhà cung cấp'],placeholder:['E.g. ABC Flour Company','VD: Công ty Bột mì ABC']},
 invoices:{button:['Add Invoice','Thêm hóa đơn'],title:['Add New Invoice','Thêm hóa đơn mới'],placeholder:['e.g., INV-001','VD: INV-001']},
 'payment-requests':{button:['Create request','Tạo duyệt chi'],title:['Create payment request','Tạo đề nghị duyệt chi'],placeholder:['E.g. January raw material purchase payment request','VD: Đề nghị chi mua NVL tháng 1']},
 'goods-receipts':{button:['Create receipt','Tạo Phiếu Nhập'],title:['Create goods receipt','Tạo Phiếu Nhập Kho']},
 'purchase-orders':{button:['Create PO (Purchasing)','Tạo PO (Mua hàng)'],title:['Create purchase order','Tạo Đơn Đặt Hàng Mới']},
};
for(const lang of ['en','vi'])for(const width of [390,1440])for(const [route,l] of Object.entries(creation))test(`${route} create dialog ${lang} ${width}, live language switch preserves input`,async()=>{
 const {c,p}=await setup(route,lang,width);const i=lang==='en'?0:1;
 try{if(route==='purchase-orders'&&width===390)await button(p,lang==='en'?'Create PO':'Tạo PO').click();else await button(p,l.button[i]).click();await p.getByRole('dialog').getByRole('heading',{name:l.title[i],exact:true}).waitFor();if(l.placeholder)await p.getByPlaceholder(l.placeholder[i]).fill('QA giữ nguyên $&');await p.evaluate(lang=>window.__fixtureSetLanguage(lang),lang==='en'?'vi':'en');await p.getByRole('dialog').getByRole('heading',{name:l.title[1-i],exact:true}).waitFor();if(l.placeholder)assert.equal(await p.getByPlaceholder(l.placeholder[1-i]).inputValue(),'QA giữ nguyên $&');assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);await p.screenshot({path:`${out}/dialog-create-${route}-${lang}-${width}.png`,fullPage:true});cases.push({route,lang,width,dialog:'create',states:['open','switch','input preserved']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`supplier validation, detail/edit, alias ${lang} ${width}`,async()=>{
 const {c,p}=await setup('suppliers',lang,width);const en=lang==='en';
 try{await button(p,en?'Add supplier':'Thêm NCC').click();await p.getByRole('dialog').locator('button[type=submit]').click();await p.getByText(en?'Please enter supplier name':'Vui lòng nhập tên nhà cung cấp',{exact:true}).waitFor();await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');await p.getByText(en?'Vui lòng nhập tên nhà cung cấp':'Please enter supplier name',{exact:true}).waitFor();await p.keyboard.press('Escape');await p.getByText('NCC giữ nguyên',{exact:true}).click();await button(p,en?'Sửa NCC':'Edit supplier').click();await p.getByText(en?'Tên gọi khác (Alias OCR)':'Alternative names (OCR aliases)',{exact:true}).waitFor();await p.getByText(en?'Chưa có alias nào.':'No aliases yet.',{exact:true}).waitFor();assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'suppliers',lang,width,states:['validation','validation switch','detail','edit','alias empty']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`payment detail and canonical partial allocation ${lang} ${width}`,async()=>{
 const {c,p}=await setup('payment-requests',lang,width);const en=lang==='en';
 try{if(width===390)await button(p,en?'Details':'Chi tiết').click();else await visible(p.getByText('QA-PR-1',{exact:true})).click();await p.getByRole('dialog').getByRole('heading',{name:en?'Payment request details':'Chi tiết đề nghị duyệt chi',exact:true}).waitFor();assert.ok((await p.getByRole('dialog').innerText()).includes('17.000'));await button(p,en?(width===390?'Payment':'Record payment'):(width===390?'Thanh toán':'Ghi nhận thanh toán')).click();await p.locator('#payment-amount').fill('7000');const confirmation=p.getByRole('alertdialog');await confirmation.getByRole('button').last().click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='record_payment_allocations'));const calls=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.rpc));const date=await p.evaluate(()=>new Date().toISOString().slice(0,10));assert.deepEqual(calls,[{rpc:'record_payment_allocations',args:{p_allocations:[{payment_request_id:'22222222-2222-4222-8222-222222222222',amount:7000}],p_payment_method:null,p_payment_date:date,p_reference_number:null,p_notes:null}}]);assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'payment-requests',lang,width,states:['detail','partial balance 17000','pay dialog','exact allocation payload 7000']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`goods receipt receive evidence guard and exact finalization ${lang} ${width}`,async()=>{
 for(const mode of ['receive-no-evidence','receive']){const {c,p,edge}=await setup('goods-receipts',lang,width,mode);const en=lang==='en';try{await visible(p.getByText('QA-GR-1',{exact:true})).click();await p.getByRole('dialog').getByRole('heading',{name:new RegExp(en?'Goods receipt details':'Chi tiết phiếu nhập kho')}).waitFor();const receive=button(p,en?'Receive + Create payable':'Nhập kho + Tạo công nợ');if(mode==='receive-no-evidence'){assert.equal(await receive.isDisabled(),true);assert.deepEqual(edge,[]);}else{await receive.click();await p.getByText(en?'Goods received and payable created for approval':'Đã nhập hàng vào kho và tạo công nợ chờ duyệt',{exact:true}).waitFor();assert.deepEqual(edge,[{receiptId:'44444444-4444-4444-8444-444444444444'}]);}assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'goods-receipts',lang,width,states:[mode,'detail','canonical quantity 2']});}finally{await c.close();}}
});
test.after(async()=>{await browser.close();await fs.writeFile(`${out}/dialogs-results.json`,JSON.stringify({cases,errors,unexpected},null,2));assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);});
