import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT || '/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM || '/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4300',out='/tmp/bmq-i18n-lanes/b-purchasing';
const errors=[],unexpected=[],cases=[];
const visible=l=>l.filter({visible:true});
const button=(p,name)=>visible(p.getByRole('button',{name,exact:true}));
async function setup(route,lang,width,mode='data'){
 const c=await browser.newContext({viewport:{width,height:1000}});await c.addInitScript(lang=>localStorage.setItem('app-language',lang),lang);
 const edge=[];await c.route('**/*',r=>{const url=r.request().url();if(url===origin+'/fixture-document.svg')return r.fulfill({body:'<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50"><text x="0" y="20">QA</text></svg>',contentType:'image/svg+xml'});if(url.startsWith(origin+'/')&&['GET','HEAD'].includes(r.request().method())&&!['fetch','xhr'].includes(r.request().resourceType()))return r.continue();if(url.startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});if(mode==='receive'&&url==='https://backend.example.invalid/functions/v1/finalize-goods-receipt'){edge.push(r.request().postDataJSON());return r.fulfill({json:{success:true,receiptId:'44444444-4444-4444-8444-444444444444',payableId:'fixture-payable',totalAmount:20000,vatAmount:0,varianceSummary:{}}});}unexpected.push(url);return r.abort();});
 const p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await p.goto(`${origin}/${route}?fixture=${mode}`);await visible(p.locator('h1')).first().waitFor();return {c,p,edge};
}
const actor='99999999-9999-4999-8999-999999999999',prId='22222222-2222-4222-8222-222222222222';
async function openRequest(p,lang,width){if(width===390)await button(p,lang==='en'?'Details':'Chi tiết').click();else await visible(p.getByText('QA-PR-1',{exact:true})).click();await p.getByRole('dialog').getByRole('heading',{name:lang==='en'?'Payment request details':'Chi tiết đề nghị duyệt chi',exact:true}).waitFor();}
for(const lang of ['en','vi'])for(const width of [390,1440])for(const action of ['approve','reject'])test(`pending PR edit and ${action}, canonical values ${lang} ${width}`,async()=>{
 const {c,p}=await setup('payment-requests',lang,width,'pending'),en=lang==='en';try{await openRequest(p,lang,width);if(action==='approve'){await button(p,en?'Edit':'Sửa').click();await p.getByRole('heading',{name:en?'Edit payment request':'Sửa đề nghị duyệt chi',exact:true}).waitFor();await p.getByPlaceholder(en?'Additional notes...':'Ghi chú thêm...').fill('Ghi chú không lưu $&');await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');assert.equal(await p.getByPlaceholder(en?'Ghi chú thêm...':'Additional notes...').inputValue(),'Ghi chú không lưu $&');await p.keyboard.press('Escape');await p.evaluate(lang=>window.__fixtureSetLanguage(lang),lang);await button(p,en?'Approve':'Duyệt').click();await p.getByRole('alertdialog').locator('[role=radio][value=cash],button#cash').click();await p.getByRole('alertdialog').getByRole('button').last().click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='approve_payment_request_with_material_controller'));const call=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='approve_payment_request_with_material_controller'));assert.deepEqual(call,{rpc:'approve_payment_request_with_material_controller',args:{p_payment_request_id:prId,p_payment_method:'cash',p_actor_id:actor}});}else{await button(p,en?'Reject':'Từ chối').click();await p.getByRole('alertdialog').getByRole('textbox').fill('Lý do giữ nguyên $&');await p.getByRole('alertdialog').getByRole('button').last().click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='payment_requests'&&c.operations.some(o=>o.method==='update')));const op=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='payment_requests').flatMap(c=>c.operations).find(o=>o.method==='update'));assert.deepEqual({...op.args[0],approved_at:'DATE'},{status:'rejected',rejection_reason:'Lý do giữ nguyên $&',approved_by:null,approved_at:'DATE'});assert.match(op.args[0].approved_at,/^\d{4}-\d{2}-\d{2}T/);}assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'payment-requests',lang,width,states:[action,'canonical payload',...(action==='approve'?['edit','edit input survives switch']:['reason preserved'])]});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`PR manual invoice nested form ${lang} ${width}`,async()=>{
 const {c,p}=await setup('payment-requests',lang,width,'uninvoiced'),en=lang==='en';try{await openRequest(p,lang,width);await button(p,en?(width===390?'Create manually':'Create invoice manually'):(width===390?'Tạo thủ công':'Tạo hoá đơn thủ công')).click();const d=p.getByRole('dialog').last();await d.getByRole('heading',{name:en?'Create invoice':'Tạo hóa đơn',exact:true}).waitFor();await d.getByText('Bột giữ nguyên',{exact:true}).waitFor();assert.equal(await d.getByPlaceholder(en?'Additional notes...':'Ghi chú thêm...').inputValue(),'Tạo từ đề nghị chi QA-PR-1');await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');await d.getByRole('heading',{name:en?'Tạo hóa đơn':'Create invoice',exact:true}).waitFor();assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'payment-requests',lang,width,states:['manual invoice child','canonical note prefill','language switch']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`approved payment PDF preview ${lang} ${width}`,async()=>{
 const {c,p}=await setup('payment-requests',lang,width),en=lang==='en';try{await visible(p.getByText('QA-PR-1',{exact:true})).waitFor();if(width===390)await button(p,en?'Select':'Chọn').click();else await visible(p.getByRole('checkbox')).first().click();await button(p,en?'Export PDF (1)':'Xuất PDF (1)').click();const d=p.getByRole('dialog');await d.getByRole('heading',{name:en?'Payment approval preview':'Xem trước Phiếu Duyệt Chi',exact:true}).waitFor();await d.getByText('Bột giữ nguyên',{exact:true}).waitFor();assert.ok((await d.innerText()).includes('22.000'));await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');await d.getByRole('heading',{name:en?'Xem trước Phiếu Duyệt Chi':'Payment approval preview',exact:true}).waitFor();assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'payment-requests',lang,width,states:['approved selection','real PDF preview','total 22000','language switch'],limitation:'PDF download bytes protected by exact source contract; external font requests not made'});}finally{await c.close();}
});
test.after(async()=>{await browser.close();await fs.writeFile(`${out}/secondary-results.json`,JSON.stringify({cases,errors,unexpected},null,2));assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);});
