import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.BMQ_PLAYWRIGHT || '/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:process.env.BMQ_CHROMIUM || '/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4300',out='/tmp/bmq-i18n-lanes/b-purchasing';
const errors=[],unexpected=[],cases=[];
const visible=l=>l.filter({visible:true});
const button=(p,name)=>visible(p.getByRole('button',{name,exact:true}));
async function setup(route,lang,width,mode='data'){
 const c=await browser.newContext({viewport:{width,height:1000}});await c.addInitScript(lang=>localStorage.setItem('app-language',lang),lang);
 const edge=[];await c.route('**/*',r=>{const url=r.request().url();if(url===origin+'/fixture-document.svg')return r.fulfill({body:'<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50"><text x="0" y="20">QA</text></svg>',contentType:'image/svg+xml'});if(url.startsWith(origin+'/')&&['GET','HEAD'].includes(r.request().method())&&!['fetch','xhr'].includes(r.request().resourceType()))return r.continue();if(url.startsWith('https://fonts.googleapis.com/'))return r.fulfill({body:'',contentType:'text/css'});if(mode==='receive'&&url==='https://backend.example.invalid/functions/v1/finalize-goods-receipt'){edge.push(r.request().postDataJSON());return r.fulfill({json:{success:true,receiptId:'44444444-4444-4444-8444-444444444444',payableId:'fixture-payable',totalAmount:20000,vatAmount:0,varianceSummary:{}}});}unexpected.push(url);return r.abort();});
 const p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));await p.goto(`${origin}/${route}?fixture=${mode}`);await visible(p.locator('h1')).first().waitFor();return {c,p,edge};
}
import { createRequire } from 'node:module';
const require=createRequire(new URL('../../../apps/web/package.json',import.meta.url));
const ExcelJS=require('exceljs');
const typedVatBaseline=JSON.parse(await fs.readFile(`${out}/invoice-baseline-parity.json`,'utf8')).payloads['baseline-invoice'];
assert.equal(typedVatBaseline.args.p_parent.total_amount,'200002000');
const actor='99999999-9999-4999-8999-999999999999';
for(const lang of ['en','vi'])for(const width of [390,1440])test(`supplier workbook bytes, import headers and exact insert ${lang} ${width}`,async()=>{
 const {c,p}=await setup('suppliers',lang,width),en=lang==='en';
 try{await p.clock.setFixedTime(new Date('2026-09-09T04:00:00Z'));await p.getByText('NCC giữ nguyên',{exact:true}).waitFor();const download=async label=>{const waiting=p.waitForEvent('download');await button(p,label).click();const file=await waiting;return fs.readFile(await file.path());};const first=await download(en?'Export Excel':'Xuất Excel');await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');const second=await download(en?'Xuất Excel':'Export Excel');assert.deepEqual(first,second);const wb=new ExcelJS.Workbook();await wb.xlsx.load(first);assert.equal(wb.worksheets[0].name,'Nhà cung cấp');assert.deepEqual(wb.worksheets[0].getRow(1).values.slice(1),['Tên NCC','Nhóm','Mô tả','SĐT','Email']);assert.equal(wb.worksheets[0].getCell('A2').value,'NCC giữ nguyên');const upload=new ExcelJS.Workbook();const sheet=upload.addWorksheet('Fixture');sheet.addRow(['Name','Category','Description','Phone','Email']);sheet.addRow(['NCC nhập giữ nguyên','Bột','Ghi chú $&','0900000001','import@example.invalid']);const buffer=Buffer.from(await upload.xlsx.writeBuffer());await p.locator('input[type=file]').setInputFiles({name:'suppliers.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await p.getByRole('dialog').getByText('NCC nhập giữ nguyên',{exact:true}).waitFor();await button(p,en?'Nhập 1 NCC':'Import 1 suppliers').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='suppliers'&&c.operations.some(o=>o.method==='insert')));const calls=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='suppliers').flatMap(c=>c.operations).filter(o=>o.method==='insert'));assert.deepEqual(calls,[{method:'insert',args:[[{name:'NCC nhập giữ nguyên',category:'Bột',description:'Ghi chú $&',phone:'0900000001',email:'import@example.invalid',created_by:actor}]]}]);cases.push({route:'suppliers',lang,width,states:['export downloaded','EN/VI byte equality','canonical XLSX headers','import preview','exact insert payload']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`supplier create preserves category and payment values ${lang} ${width}`,async()=>{
 const {c,p}=await setup('suppliers',lang,width),en=lang==='en';try{await button(p,en?'Add supplier':'Thêm NCC').click();await p.getByPlaceholder(en?'E.g. ABC Flour Company':'VD: Công ty Bột mì ABC').fill('NCC QA');await p.getByRole('dialog').getByRole('combobox').click();await p.getByRole('option',{name:'Bột',exact:true}).click();await p.getByRole('radio',{name:en?'Cash':'Tiền mặt',exact:true}).click();await p.getByRole('dialog').locator('input[type=number]').fill('30');await p.getByRole('dialog').locator('button[type=submit]').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.table==='suppliers'&&c.operations.some(o=>o.method==='insert')));const insert=await p.evaluate(()=>window.__fixtureCalls.filter(c=>c.table==='suppliers').flatMap(c=>c.operations).find(o=>o.method==='insert').args[0]);assert.deepEqual(insert,{created_by:actor,name:'NCC QA',short_code:'NQ',category:'Bột',description:null,phone:null,email:null,bank_account_name:null,default_payment_method:'cash',contract_url:null,payment_terms_days:30});cases.push({route:'suppliers',lang,width,states:['create','category remains Bột','cash canonical','payment terms 30','exact insert payload']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`invoice detail/edit and typed-VAT baseline parity (existing defect) ${lang} ${width}`,async()=>{
 const {c,p}=await setup('invoices',lang,width),en=lang==='en';try{await visible(p.getByText('QA-INV-1',{exact:true})).click();await p.getByRole('dialog').getByText('Bột giữ nguyên',{exact:true}).waitFor();await button(p,en?'Edit':'Chỉnh sửa').click();await p.getByRole('dialog').getByRole('heading',{name:en?'Edit Invoice':'Chỉnh sửa hóa đơn',exact:true}).waitFor();assert.equal(await p.getByPlaceholder(en?'Additional notes...':'Ghi chú thêm...').inputValue(),'Ghi chú giữ nguyên');await p.keyboard.press('Escape');await button(p,en?'Add Invoice':'Thêm hóa đơn').click();await p.getByPlaceholder(en?'e.g., INV-001':'VD: INV-001').fill('QA-NEW-INV');await p.getByPlaceholder(en?'Product name':'Tên sản phẩm',{exact:true}).fill('Bột mới giữ nguyên');await p.getByLabel(en?'Quantity':'Số lượng',{exact:true}).fill('2');await p.getByLabel(en?'Unit Price':'Đơn giá',{exact:true}).fill('10000');await p.getByLabel(en?'VAT Amount (VND)':'Tiền VAT (VND)',{exact:true}).fill('2000');await p.getByPlaceholder(en?'Additional notes...':'Ghi chú thêm...').fill('Ghi chú mới $&');await button(p,en?'Create Invoice':'Tạo hóa đơn').click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='create_invoice_with_material_controller'));const call=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='create_invoice_with_material_controller'));assert.equal(call.args.p_actor_id,actor);assert.deepEqual({...call.args.p_parent,invoice_date:'DATE'},{invoice_number:'QA-NEW-INV',invoice_date:'DATE',supplier_id:null,subtotal:20000,vat_amount:'2000',total_amount:'200002000',image_url:null,payment_slip_url:null,notes:'Ghi chú mới $&'});assert.match(call.args.p_parent.invoice_date,/^\d{4}-\d{2}-\d{2}$/);assert.deepEqual(call.args.p_items,[{product_code:null,product_name:'Bột mới giữ nguyên',unit:'kg',quantity:2,unit_price:10000,inventory_item_id:null,raw_product_name:'Bột mới giữ nguyên',suggested_standard_cost_code:null,confirmed_standard_cost_code:null,standard_cost_code_type:null,canonical_cost_item_name:null,canonical_cost_item_source:null,cost_category_code:null,cost_product_line:null,cost_allocation_rule:null,cost_review_routing:'none',unit_conversion_note:null,matched_finished_skus:null,ocr_classification_json:null}]);assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'invoices',lang,width,states:['detail','edit notes preserved','create','baseline defect preserved: typed VAT is string and total concatenates','canonical RPC parent and items']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`Drive configuration error switches reactively ${lang} ${width}`,async()=>{
 const {c,p}=await setup('payment-requests',lang,width),en=lang==='en';try{await visible(p.getByTitle(en?'Import from Google Drive':'Nhập từ Google Drive',{exact:true})).click();const vi='Chưa cấu hình folder Bank Receipts. Vui lòng cấu hình trong Cài đặt → Google Drive Integration',english='Bank Receipts folder is not configured. Configure it in Settings → Google Drive Integration';await p.getByText(en?english:vi,{exact:true}).waitFor();await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');await p.getByText(en?vi:english,{exact:true}).waitFor();assert.deepEqual(await p.evaluate(()=>window.__fixtureUnexpected),[]);cases.push({route:'payment-requests',lang,width,states:['Drive actual dialog','missing configuration','persistent error switches']});}finally{await c.close();}
});
for(const lang of ['en','vi'])for(const width of [390,1440])test(`PO detail and canonical approval ${lang} ${width}`,async()=>{
 const {c,p}=await setup('purchase-orders',lang,width),en=lang==='en';try{await visible(p.getByText('QA-PO-1',{exact:true})).first().click();await visible(p.getByRole('dialog').getByText('Bột giữ nguyên',{exact:true})).first().waitFor();if(width===390){const check=p.getByRole('dialog').getByRole('checkbox').first();await check.check();await p.evaluate(lang=>window.__fixtureSetLanguage(lang),en?'vi':'en');assert.equal(await check.isChecked(),true);await p.evaluate(lang=>window.__fixtureSetLanguage(lang),lang);await button(p,en?'Approve PO':'Duyệt PO').click();}else{await button(p,en?'Edit':'Chỉnh sửa').click();await p.getByRole('heading',{name:en?'Edit purchase order':'Chỉnh sửa Đơn Đặt Hàng',exact:true}).waitFor();await p.keyboard.press('Escape');await button(p,en?'Send order':'Gửi đơn hàng').click();}const dialog=p.getByRole('alertdialog');await dialog.getByRole('button',{name:en?'Send order':'Gửi đơn',exact:true}).click();await p.waitForFunction(()=>window.__fixtureCalls.some(c=>c.rpc==='update_purchase_order_status_with_material_controller'));const call=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='update_purchase_order_status_with_material_controller'));assert.deepEqual(call,{rpc:'update_purchase_order_status_with_material_controller',args:{p_purchase_order_id:'33333333-3333-4333-8333-333333333333',p_status:'sent',p_actor_id:actor}});cases.push({route:'purchase-orders',lang,width,states:['detail',width===390?'checklist preserved across language switch':'edit','send confirmation','canonical sent RPC']});}finally{await c.close();}
});
test.after(async()=>{await browser.close();await fs.writeFile(`${out}/workflows-results.json`,JSON.stringify({cases,errors,unexpected},null,2));assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);});
