# Generated by Django 5.2.11 on 2026-02-07 13:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('allocation_method', models.CharField(choices=[('percentage_of_prime_cost', 'Percentage of Prime Cost'), ('per_unit_produced', 'Per Unit Produced'), ('direct_assign', 'Direct Assignment')], default='per_unit_produced', max_length=50)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Overhead Category',
                'verbose_name_plural': 'Overhead Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProductionVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveIntegerField()),
                ('total_units_produced', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Monthly Production Volume',
                'verbose_name_plural': 'Monthly Production Volumes',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='OverheadCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='overhead.overheadcategory')),
            ],
            options={
                'verbose_name': 'Overhead Cost',
                'verbose_name_plural': 'Overhead Costs',
                'ordering': ['-year', '-month'],
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
