// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const lovableAuth = createLovableAuth({
  oauthBrokerUrl: "https://oauth.lovable.app/~oauth/initiate",
  supportedOAuthOrigins: ["https://oauth.lovable.app"],
});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};

/**
 * Handle OAuth callback from URL hash after Google redirect.
 * Call this on Auth page mount to extract tokens and set session.
 */
export async function handleOAuthCallback(): Promise<{
  handled: boolean;
  error?: Error;
}> {
  const hash = window.location.hash;
  
  // Check if URL has OAuth tokens
  if (!hash || !hash.includes('access_token')) {
    return { handled: false };
  }

  const params = new URLSearchParams(hash.substring(1));
  const access_token = params.get('access_token');
  const refresh_token = params.get('refresh_token');

  if (!access_token || !refresh_token) {
    return { handled: false };
  }

  try {
    await supabase.auth.setSession({ access_token, refresh_token });
    // Clean URL hash for security
    window.history.replaceState(null, '', window.location.pathname);
    return { handled: true };
  } catch (e) {
    return { 
      handled: true, 
      error: e instanceof Error ? e : new Error(String(e)) 
    };
  }
}
