# Generated by Django 5.2.11 on 2026-02-07 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('approved', 'Approved'), ('active', 'Active'), ('archived', 'Archived')], default='calculated', max_length=20)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ingredient_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculation_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown for audit trail')),
                ('calculated_by', models.CharField(default='system', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_costs', to='products.product')),
            ],
            options={
                'verbose_name': 'SKU Cost',
                'verbose_name_plural': 'SKU Costs',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InflationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_cost_change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ingredient_cost_change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labor_cost_change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('labor_cost_change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overhead_cost_change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('overhead_cost_change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_cost_change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost_change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('previous_sku_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_inflation', to='costs.skucost')),
                ('sku_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflation_records', to='costs.skucost')),
            ],
            options={
                'verbose_name': 'Inflation Tracking',
                'verbose_name_plural': 'Inflation Tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(choices=[('ingredient', 'Ingredient'), ('labor', 'Labor'), ('overhead', 'Overhead')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage_of_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional component-specific details')),
                ('sku_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='costs.skucost')),
            ],
            options={
                'verbose_name': 'Cost Component',
                'verbose_name_plural': 'Cost Components',
                'ordering': ['component_type', '-amount'],
            },
        ),
    ]
