// Synthetic backend only. Actual pages and query/mutation hooks remain imported.
const mode=new URLSearchParams(location.search).get('mode')||'data';
const today=new Date().toISOString().slice(0,10);
const employee={employee_code:'NV-01',employee_name:'Tên giữ nguyên $&',department:'Bộ phận giữ nguyên'};
const run={id:'run-1',period_code:'PAY-01',period_name:'Kỳ giữ nguyên',period_from:'2026-09-01',period_to:'2026-09-30',status:'calculated',total_gross:10000000,total_deductions:200000,total_net:9800000};
const tables:Record<string,unknown[]>={
 profiles:[{user_id:'owner-1',full_name:'Owner giữ nguyên',email:'owner@example.invalid'},{user_id:'staff-1',full_name:'Tên giữ nguyên $&',email:'staff@example.invalid'}],
 user_roles:[{id:'role-1',user_id:'owner-1',role:location.search.includes('readonly')?'viewer':'owner'},{id:'role-2',user_id:'staff-1',role:'staff'}],user_module_permissions:[{user_id:'staff-1',module_key:'dashboard',can_view:true,can_edit:false}],
 attendance_periods:[{id:'period-1',period_name:'Kỳ giữ nguyên',date_from:'2026-09-01',date_to:'2026-09-30',status:mode==='locked'?'locked':'open'}],
 attendance_records:[{...employee,id:'record-1',work_date:today,status:'missing_check_out',actual_check_in:today+'T08:00:00+07:00',actual_check_out:null,minutes_late:10,minutes_early_leave:0,missing_check_in:false,missing_check_out:true,locked_by_hr:false,source_type:'mobile_gps',source_actor_type:'report_staff',source_distance_m:10,source_accuracy_m:5}],
 attendance_events:[{...employee,id:'event-1',event_type:'check_in',event_time:today+'T08:00:00+07:00',source:'qr'}],
 attendance_shift_assignments:[{...employee,id:'assignment-1',shift_id:'shift-1',work_date:today,status:'assigned',attendance_shifts:{start_time:'08:00:00',end_time:'17:00:00',grace_minutes:5}}],
 attendance_shifts:[{id:'shift-1',shift_code:'CA-01',shift_name:'Ca giữ nguyên',start_time:'08:00:00',end_time:'17:00:00'}],
 payroll_runs:[run],payroll_lines:[{...employee,id:'line-1',payroll_run_id:'run-1',total_hours_worked:160,total_minutes_late:10,base_amount:10000000,late_deduction:200000,adjustment_total:0,net_amount:9800000,total_shifts:20,days_present:20,total_days_present:20,total_shifts_full:20,total_shifts_partial:2,wage_type_snapshot:"monthly"}],
 employee_wage_profiles:[{...employee,id:'profile-1',wage_type:'monthly',base_monthly_salary:10000000,hourly_rate:50000,per_shift_rate:400000,standard_days_per_month:26,standard_hours_per_day:8,partial_shift_floor:0.5,effective_from:'2026-09-01',effective_to:null,is_active:true}],
 v_payroll_period_summary:[{...run,payroll_run_id:'run-1',employee_count:1,total_base:10000000,total_late_deduction:200000,total_adjustments:0,total_withholdings:200000}],
 v_payroll_journal_draft:[{...employee,payroll_run_id:'run-1',period_code:'PAY-01',account_code:'622',account_name:'Chi phí giữ nguyên',entry_type:'debit',amount:10000000}],
 v_labor_cost_by_sku:[{sku_id:'sku-1',sku_code:'SKU-01',product_name:'Sản phẩm giữ nguyên',period_month:'2026-09-01',period_code:'PAY-01',total_qty_produced:100,total_labor_cost:10000000,cost_per_unit:100000,source_account_code:'622',target_account_code:'154',target_account_name:'Giữ nguyên'}],
 app_settings:mode === "empty" ? [] : [{key:"google_drive_connected_email",value:"drive@example.invalid"},{key:"google_drive_po_folder",value:"https://drive.google.com/drive/folders/fixture"}],drive_sync_config:[{folder_type:'po',last_synced_at:null,last_sync_status:'success'}],drive_file_index:[],
};
(window as any).__fixtureCalls=[];
function record(call:unknown){(window as any).__fixtureCalls.push(call);}
function result(data:unknown,single=false){if(mode==='loading')return new Promise(()=>{});if(mode==='error')return Promise.resolve({data:null,error:{message:'SERVER giữ nguyên $&',code:'fixture'}});return Promise.resolve({data:mode==='empty'?(single?null:[]):data,error:null,count:0});}
class Query {
 op='read';payload:unknown;single=false;filters:Record<string,unknown>={};
 constructor(public table:string){if(!(table in tables)&&!['attendance_adjustments'].includes(table))throw Error('Unexpected table '+table);}
 select(){return this;}order(){return this;}limit(){return this;}range(){return this;}gte(){return this;}lte(){return this;}or(){return this;}in(){return this;}
 eq(key:string,value:unknown){this.filters[key]=value;return this;}
 maybeSingle(){this.single=true;return this;}singleResult(){this.single=true;return this;}
 insert(value:unknown){this.op='insert';this.payload=value;return this;}update(value:unknown){this.op='update';this.payload=value;return this;}upsert(value:unknown){this.op='upsert';this.payload=value;return this;}delete(){this.op='delete';return this;}
 then(resolve:any,reject:any){record({table:this.table,op:this.op,payload:this.payload,filters:this.filters});let rows=tables[this.table]||[];if(this.table==='user_roles'&&this.filters.user_id)rows=rows.filter((r:any)=>r.user_id===this.filters.user_id);const data=this.single?(rows[0]||null):rows;return (this.op!=='read'&&mode==='save-error'?Promise.resolve({data:null,error:new Error('SERVER giữ nguyên $&')}):result(data,this.single)).then(resolve,reject);}
}
export const supabase={from:(table:string)=>new Query(table),rpc:(name:string,args:unknown)=>{record({rpc:name,args});if(name==='get_mobile_gps_attendance_pilot_dashboard')return result({capability_available:true,events:mode==='gps-data'?[{...employee,id:'gps-1',work_date:today,actor_type:'report_staff',geofence_name:'Điểm giữ nguyên',geofence_code:'LOC-1',geofence_location_type:'warehouse',geofence_radius_m:100,decision:'accepted',reason_code:'within_geofence',distance_m_rounded:10,accuracy_m_rounded:5,has_override:true}]:[],metrics:{event_count:1,accepted_count:1,rejected_count:0,low_accuracy_count:0,outside_radius_count:0,duplicate_count:0,override_count:1,success_rate:1},pagination:{returned_count:0,total_count:0,limit:50,has_next_page:false}});if(name==='get_payroll_gps_attendance_preview')return result({capability_available:true,rows:mode==='gps-data'?[{...employee,gps_valid_days:20,attendance_present_days:19,payroll_total_days_present:19,gps_vs_attendance_days_delta:1,gps_vs_payroll_days_delta:1,attendance_locked_days:2,attendance_manual_days:3,override_days:1,payroll_status:'calculated'}]:[],metrics:{gps_valid_days:20,attendance_present_days:19,discrepancy_employee_count:1}});if(name==='payroll_calculate_run')return result([{processed_employees:1,lines_written:1}]);if(name==='attendance_copy_week_roster')return result([{inserted_count:1,skipped_count:0}]);throw Error('Unexpected RPC '+name);},auth:{getUser:async()=>({data:{user:{id:'owner-1'}}}),getSession:async()=>({data:{session:{access_token:'fixture-only'}}}),refreshSession:async()=>location.search.includes('auth-error')?{data:{session:null},error:new Error('fixture auth refresh failed')}:{data:{session:{access_token:'fixture-only'}},error:null}},functions:{invoke:async(name:string,args:unknown)=>{record({invoke:name,args});if(!['user-delete-member','migration-storage-manifest'].includes(name))throw Error('Unexpected function '+name);return {data:{success:true,files:[]},error:mode==='save-error'?{message:'SERVER giữ nguyên $&'}:null};}},storage:{from:()=>{throw Error('Unexpected storage request');}}};
