import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const{chromium}=await import('/home/ubuntu/bmq-payment-preview/node_modules/playwright/index.mjs');const browser=await chromium.launch({executablePath:'/home/ubuntu/.cache/ms-playwright/chromium-1234/chrome-linux/chrome',args:['--no-sandbox']});
const origin='http://127.0.0.1:4302',cases=[],unexpected=[],errors=[];
const visible=l=>l.filter({visible:true});const button=(p,name)=>visible(p.getByRole('button',{name,exact:true}));
async function setup(page,lang,width,mode='data',readonly=false){const context=await browser.newContext({viewport:{width,height:1000}}),calls=[];await context.addInitScript(lang=>{localStorage.setItem('app-language',lang);window.open=(...args)=>{window.__opened=args;return null}},lang);let confirms=0;await context.route('**/*',async route=>{const request=route.request(),url=request.url();if(url.startsWith(origin+'/mock/functions/v1/')){const body=request.postDataJSON();calls.push({url,body});if(page==='source'&&url.endsWith('/export-daily-revenue-sheet'))return route.fulfill({status:mode==='export-http'?503:200,json:mode==='export-http'?{}:mode==='export-error'?{error:'SERVER giữ nguyên $&'}:{success:true,webViewLink:'https://example.invalid/sheet',fileName:'Tên file giữ nguyên',folderName:'01/04/2026',rowCount:22,grossRevenue:286000}});if(page==='parse'&&url.endsWith('/revenue-monthly-parse-preview')){if(mode==='parse-error')return route.fulfill({status:500,json:{error:'SERVER giữ nguyên $&'}});if(body.action==='preview_daily_compare')return route.fulfill({json:{runId:'run-1',period:'2026-04',previewSummary:{period:'2026-04',rows:2,ledgerRows:2,grossRevenue:26000,dashboardGrossRevenue:26000,quantity:4,reviewFlaggedRows:1,channels:[{channel:'ĐẠI LÝ',rows:2,grossRevenue:26000,quantity:4,reviewFlaggedRows:1}]}}});if(body.action==='confirm_daily_post'){if(mode==='replace'&&confirms++===0)return route.fulfill({status:409,json:{requiresOverwriteConfirmation:true,existing:[{id:'old',period:'2026-04',status:'approved'}]}});return route.fulfill({json:{summary:{posted_line_count:2,gross_total:26000}}})}if(body.action==='cancel_daily_preview')return route.fulfill({json:{success:true}})}unexpected.push(url);return route.abort()}
if(url.startsWith(origin+'/'))return route.continue();if(url.startsWith('https://fonts.googleapis.com/'))return route.fulfill({body:'',contentType:'text/css'});unexpected.push(url);return route.abort()});const p=await context.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));await p.goto(`${origin}/?page=${page}&period=2026-04&revenue_date=2026-04-01&scope=controlled_ledger&fixture=${mode}&readonly=${readonly?1:0}`);return{p,context,calls};}
for(const lang of ['en','vi'])for(const width of [390,1440]){
 test(`source actions ${lang} ${width}: manual payload, edit preservation, export and reactive in-flight dialog`,async()=>{const{p,context,calls}=await setup('source',lang,width);try{
 await button(p,lang==='en'?'+ Add revenue row':'+ Thêm dòng doanh thu').click();await p.locator('#manual-channel').selectOption('ĐẠI LÝ');await p.locator('#manual-customer').selectOption('Khách hàng giữ nguyên');await p.locator('#manual-qty').fill('3');assert.equal(await p.locator('#manual-gross').inputValue(),'19500');await p.locator('#manual-item-note').fill('Ghi chú giữ nguyên $&');const other=lang==='en'?'vi':'en';await p.evaluate(other=>document.querySelector('nav[aria-label="Fixture language"]').querySelectorAll('button')[other==='vi'?0:1].click(),other);await p.getByRole('heading',{name:other==='en'?'Add manual revenue row':'Thêm dòng doanh thu thủ công',exact:true}).waitFor();assert.equal(await p.locator('#manual-channel').inputValue(),'ĐẠI LÝ');assert.equal(await p.locator('#manual-gross').inputValue(),'19500');await button(p,other==='en'?'Add to controlled revenue':'Thêm vào Doanh thu đã kiểm soát').click();await p.getByRole('dialog').waitFor({state:'hidden'});const add=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='add_manual_revenue_ledger_line'));assert.deepEqual(add.args._payload,{period:'2026-04',revenue_date:'2026-04-01',channel:'ĐẠI LÝ',customer_name:'Khách hàng giữ nguyên',product_name:'Bánh mì que',item_note:'Ghi chú giữ nguyên $&',quantity:3,unit_price:6500,gross_revenue:19500,manual_entry_type:'missing_po_email',reason_code:'staff_forgot_po_email',evidence_note:'Bổ sung doanh thu thủ công từ vận hành. Khách: Khách hàng giữ nguyên. Sản phẩm: Bánh mì que. SL 3, đơn giá 6500, doanh thu 19500. Ghi chú: Ghi chú giữ nguyên $&.',evidence_url:null});assert.equal(add.args._note,add.args._payload.evidence_note);
 await button(p,other==='en'?'Edit':'Sửa').first().click();await p.locator('#quantity').fill('4');await p.locator('#audit-note').fill('Đối chiếu giữ nguyên');await button(p,other==='en'?'Save & record log':'Lưu & ghi log').click();await p.getByRole('dialog').waitFor({state:'hidden'});const edit=await p.evaluate(()=>window.__fixtureCalls.find(c=>c.rpc==='edit_revenue_ledger_line'));assert.equal(edit.args._patch.quantity,4);assert.equal(edit.args._patch.gross_revenue,13000);assert.deepEqual(['approval_status','audit_status','confidence_status','review_status','reconciliation_status'].map(k=>edit.args._patch[k]),['approved','adjusted','manual_review','resolved','manual_override']);assert.equal(edit.args._patch.raw_payload.audit_decision.before.quantity,2);assert.equal(edit.args._patch.raw_payload.audit_decision.before.gross_revenue,13000);
 await button(p,'Export Google Sheet').click();await p.getByText(other==='en'?'Google Sheet export status':'Trạng thái export Google Sheet',{exact:true}).waitFor();await p.getByText(other==='en'?'Created Tên file giữ nguyên in folder 01/04/2026.':'Đã tạo Tên file giữ nguyên trong thư mục 01/04/2026.',{exact:true}).waitFor();assert.deepEqual(calls[0].body,{revenueDate:'2026-04-01'});assert.deepEqual(await p.evaluate(()=>window.__opened),['https://example.invalid/sheet','_blank','noopener,noreferrer']);await button(p,lang.toUpperCase()).click();await p.getByText(lang==='en'?'Created Tên file giữ nguyên in folder 01/04/2026.':'Đã tạo Tên file giữ nguyên trong thư mục 01/04/2026.',{exact:true}).waitFor();cases.push({page:'source',lang,width,states:['manual add','edit','audit payload','export','reactive dialog/status'],passed:true});
 }finally{await context.close()}});
 for(const mode of ['approve','replace','reject','parse-error'])test(`parse ${mode} ${lang} ${width}: owner action payload and dialog`,async()=>{const{p,context,calls}=await setup('parse',lang,width,mode);try{await button(p,lang==='en'?'Parse day & preview':'Parse ngày & xem preview').click();if(mode==='parse-error'){await p.getByText('SERVER giữ nguyên $&',{exact:true}).waitFor()}else{await p.getByText(lang==='en'?'Summary by dashboard channel':'Summary theo kênh dashboard',{exact:true}).waitFor();assert.ok((await p.getByRole('dialog').innerText()).includes('26.000'));if(mode==='reject'){await button(p,lang==='en'?'Reject':'Từ chối').click();assert.deepEqual(calls.at(-1).body,{action:'cancel_daily_preview',runId:'run-1'})}else{await button(p,lang==='en'?'Approve & add to dashboard':'Approve & đưa vào dashboard').click();assert.deepEqual(calls.at(-1).body,{action:'confirm_daily_post',runId:'run-1',overwrite:false});if(mode==='replace'){await button(p,lang==='en'?'Replace current version & approve':'Replace bản hiện tại & approve').click();assert.deepEqual(calls.at(-1).body,{action:'confirm_daily_post',runId:'run-1',overwrite:true})}await p.getByText(lang==='en'?'Parse results saved':'Đã lưu kết quả parse',{exact:true}).waitFor();const other=lang==='en'?'vi':'en';await p.evaluate(other=>document.querySelector('nav').querySelectorAll('button')[other==='vi'?0:1].click(),other);await p.getByText(other==='en'?'Parse results saved':'Đã lưu kết quả parse',{exact:true}).waitFor()}}
assert.equal(calls[0].body.action,'preview_daily_compare');assert.match(calls[0].body.revenueDate,/^\d{4}-\d{2}-\d{2}$/);cases.push({page:'parse',lang,width,state:mode,passed:true});}finally{await context.close()}});
 for(const mode of ['export-error','export-http'])test(`source ${mode} ${lang} ${width}: reactive persistent error and verbatim server text`,async()=>{const{p,context,calls}=await setup('source',lang,width,mode);try{await button(p,'Export Google Sheet').click();
const message=l=>mode==='export-error'?(l==='en'?'Google Sheet export failed: SERVER giữ nguyên $&':'Export Google Sheet thất bại: SERVER giữ nguyên $&'):(l==='en'?'Google Sheet export failed: Export failed HTTP 503':'Export Google Sheet thất bại: Export thất bại HTTP 503');
await p.getByText(message(lang),{exact:true}).waitFor();const other=lang==='en'?'vi':'en';await button(p,other.toUpperCase()).click();await p.getByText(message(other),{exact:true}).waitFor();assert.deepEqual(calls[0].body,{revenueDate:'2026-04-01'});assert.equal(await p.evaluate(()=>window.__opened),undefined);cases.push({page:'source',lang,width,state:mode,passed:true});}finally{await context.close()}});
 test(`permissions ${lang} ${width}: readonly blocks writes`,async()=>{for(const page of ['point','source','parse']){const{p,context,calls}=await setup(page,lang,width,'data',true);try{if(page==='source')assert.equal(await button(p,lang==='en'?'+ Add revenue row':'+ Thêm dòng doanh thu').isDisabled(),true);if(page==='parse')assert.equal(await button(p,lang==='en'?'Parse day & preview':'Parse ngày & xem preview').isDisabled(),true);if(page==='point'){await button(p,lang==='en'?'View report':'Xem báo cáo').click();assert.equal(await button(p,lang==='en'?'Save changes':'Lưu thay đổi').count(),0)}assert.deepEqual(calls,[]);cases.push({page,lang,width,state:'readonly',passed:true})}finally{await context.close()}}});
}
test.after(async()=>{await browser.close();await fs.writeFile('/tmp/bmq-i18n-lanes/b-revenue/actions-results.json',JSON.stringify({cases,errors,unexpected},null,2));assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[])});
