-- Canonical schema version 001. Generated from canonical.py; no source/customer data.
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE TABLE IF NOT EXISTS silver.customers ("customer_id" VARCHAR, "external_customer_id" VARCHAR, "full_name" VARCHAR, "email" VARCHAR, "phone" VARCHAR, "customer_type" VARCHAR, "status" VARCHAR, "first_order_at" TIMESTAMPTZ, "last_order_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,customer_id));
CREATE TABLE IF NOT EXISTS silver.products ("product_id" VARCHAR, "external_product_id" VARCHAR, "sku" VARCHAR, "name" VARCHAR, "category" VARCHAR, "subcategory" VARCHAR, "brand" VARCHAR, "unit" VARCHAR, "list_price" DECIMAL(24,6), "standard_cost" DECIMAL(24,6), "status" VARCHAR, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,product_id));
CREATE TABLE IF NOT EXISTS silver.locations ("location_id" VARCHAR, "external_location_id" VARCHAR, "name" VARCHAR, "location_type" VARCHAR, "address" VARCHAR, "city" VARCHAR, "region" VARCHAR, "country" VARCHAR, "timezone" VARCHAR, "status" VARCHAR, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,location_id));
CREATE TABLE IF NOT EXISTS silver.orders ("order_id" VARCHAR, "external_order_id" VARCHAR, "customer_id" VARCHAR, "location_id" VARCHAR, "channel" VARCHAR, "status" VARCHAR, "currency" VARCHAR, "subtotal" DECIMAL(24,6), "discount_amount" DECIMAL(24,6), "tax_amount" DECIMAL(24,6), "service_fee" DECIMAL(24,6), "shipping_amount" DECIMAL(24,6), "gross_amount" DECIMAL(24,6), "net_amount" DECIMAL(24,6), "cost_amount" DECIMAL(24,6), "gross_profit" DECIMAL(24,6), "ordered_at" TIMESTAMPTZ, "completed_at" TIMESTAMPTZ, "cancelled_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,order_id));
CREATE TABLE IF NOT EXISTS silver.order_items ("order_item_id" VARCHAR, "order_id" VARCHAR, "product_id" VARCHAR, "quantity" DECIMAL(24,6), "unit_price" DECIMAL(24,6), "discount_amount" DECIMAL(24,6), "net_amount" DECIMAL(24,6), "unit_cost" DECIMAL(24,6), "cost_amount" DECIMAL(24,6), "gross_profit" DECIMAL(24,6), "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,order_item_id));
CREATE TABLE IF NOT EXISTS silver.payments ("payment_id" VARCHAR, "external_payment_id" VARCHAR, "order_id" VARCHAR, "customer_id" VARCHAR, "payment_method" VARCHAR, "status" VARCHAR, "currency" VARCHAR, "amount" DECIMAL(24,6), "paid_at" TIMESTAMPTZ, "refunded_amount" DECIMAL(24,6), "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,payment_id));
CREATE TABLE IF NOT EXISTS silver.inventory_movements ("inventory_movement_id" VARCHAR, "product_id" VARCHAR, "location_id" VARCHAR, "movement_type" VARCHAR, "quantity" DECIMAL(24,6), "unit_cost" DECIMAL(24,6), "reference_type" VARCHAR, "reference_id" VARCHAR, "event_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,inventory_movement_id));
CREATE TABLE IF NOT EXISTS silver.inventory_snapshots ("snapshot_id" VARCHAR, "product_id" VARCHAR, "location_id" VARCHAR, "quantity_on_hand" DECIMAL(24,6), "quantity_reserved" DECIMAL(24,6), "quantity_available" DECIMAL(24,6), "snapshot_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,snapshot_id));
CREATE TABLE IF NOT EXISTS silver.suppliers ("supplier_id" VARCHAR, "external_supplier_id" VARCHAR, "name" VARCHAR, "email" VARCHAR, "phone" VARCHAR, "status" VARCHAR, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,supplier_id));
CREATE TABLE IF NOT EXISTS silver.purchases ("purchase_id" VARCHAR, "supplier_id" VARCHAR, "location_id" VARCHAR, "status" VARCHAR, "currency" VARCHAR, "subtotal" DECIMAL(24,6), "tax_amount" DECIMAL(24,6), "total_amount" DECIMAL(24,6), "ordered_at" TIMESTAMPTZ, "received_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,purchase_id));
CREATE TABLE IF NOT EXISTS silver.employees ("employee_id" VARCHAR, "external_employee_id" VARCHAR, "location_id" VARCHAR, "full_name" VARCHAR, "role" VARCHAR, "status" VARCHAR, "hire_date" TIMESTAMPTZ, "termination_date" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,employee_id));
CREATE TABLE IF NOT EXISTS silver.expenses ("expense_id" VARCHAR, "location_id" VARCHAR, "category" VARCHAR, "subcategory" VARCHAR, "vendor" VARCHAR, "currency" VARCHAR, "amount" DECIMAL(24,6), "expense_at" TIMESTAMPTZ, "description" VARCHAR, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,expense_id));
CREATE TABLE IF NOT EXISTS silver.conversations ("conversation_id" VARCHAR, "customer_id" VARCHAR, "channel" VARCHAR, "external_thread_id" VARCHAR, "status" VARCHAR, "started_at" TIMESTAMPTZ, "last_message_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,conversation_id));
CREATE TABLE IF NOT EXISTS silver.messages ("message_id" VARCHAR, "conversation_id" VARCHAR, "sender_type" VARCHAR, "sender_id" VARCHAR, "direction" VARCHAR, "content" VARCHAR, "sent_at" TIMESTAMPTZ, "tenant_id" VARCHAR, "source_system" VARCHAR, "source_record_id" VARCHAR, "source_timezone" VARCHAR, "created_at" TIMESTAMPTZ, "updated_at" TIMESTAMPTZ, "metadata" VARCHAR, "is_deleted" BOOLEAN, "deleted_at" TIMESTAMPTZ, PRIMARY KEY(tenant_id,message_id));
